#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Mostar.Models.AVR_IGLim_Capacitive.Generator_fmu
 Dymola Version 2019 FD01 (64-bit), 2018-10-10 translated this at Fri Sep 24 09:26:29 2021

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0);
DYMOLA_STATIC double   OpenIPSL_NonElectrical_Functions_SE(double  u0_0, double 
   SE10_0, double  SE20_0, double  E10_0, double  E20_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Math.atan3
discrete input Real u1;
discrete input Real u2;
discrete input Real y0(start = 0, unit = "rad", displayUnit = "deg") "y shall be in the range: -pi < y-y0 <= pi";
discrete output Real y(unit = "rad", displayUnit = "deg");
protected 
constant Real pi2 = 6.283185307179586;
discrete Real w;
public 
algorithm 
w := atan2(u1, u2);
if (y0 == 0) then 
y := w;
else
y := w+pi2*integer((3.141592653589793+y0-w)/pi2);
end if;
end Modelica.Math.atan3;

  */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0) {
  PushContext("Modelica.Math.atan3")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    double   pi20_0;
    double   w0_0;
    y0_0=0;
    pi20_0 = 6.283185307179586;
    w0_0=0;
    /* Start of real code */
      w0_0 = atan2(u10_0, u20_0);
      if (y00_0 == 0) {
        y0_0 = w0_0;
      }
      else{
        y0_0 = w0_0+pi20_0*real2integer(divmacro(3.141592653589793+y00_0-w0_0,
          "3.141592653589793+y0-w",pi20_0,"pi2"));
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function OpenIPSL.NonElectrical.Functions.SE
discrete input Real u "Unsaturated Input";
discrete input Real SE1;
discrete input Real SE2;
discrete input Real E1;
discrete input Real E2;
discrete output Real sys "Saturated Output";
protected 
parameter Real a = (if SE2 <> 0 then sqrt(SE1*E1/(SE2*E2)) else 0);
parameter Real A = E2-(E1-E2)/(a-1);
parameter Real B = (if abs(E1-E2) < 1E-15 then 0 else SE2*E2*(a-1)^2/(E1-E2)^2);
public 
algorithm 
if (SE1 == 0.0 or u <= 0.0) then 
sys := 0.0;
else
if (u <= A) then 
sys := 0.0;
else
sys := B*(u-A)^2/u;
end if;
end if;
end OpenIPSL.NonElectrical.Functions.SE;

  */
DYMOLA_STATIC double   OpenIPSL_NonElectrical_Functions_SE(double  u0_0, double 
   SE10_0, double  SE20_0, double  E10_0, double  E20_0) {
  PushContext("OpenIPSL.NonElectrical.Functions.SE")
  {
    /* Declare outputs and temporaries */
    double   sys0_0;
    double   a0_0;
    double   A0_0;
    double   B0_0;
    sys0_0=0;
    a0_0 = IF SE20_0 != 0 THEN sqrtGuarded(divmacro(SE10_0*E10_0,"SE1*E1",SE20_0
      *E20_0,"SE2*E2"),"SE1*E1/(SE2*E2)") ELSE 0;
    A0_0 = E20_0-divmacro(E10_0-E20_0,"E1-E2",a0_0-1,"a-1");
    B0_0 = IF fabs(E10_0-E20_0) < 1E-15 THEN 0 ELSE divmacro(SE20_0*E20_0*sqr(
      a0_0-1),"SE2*E2*(a-1)^2",sqr(E10_0-E20_0),"(E1-E2)^2");
    /* Start of real code */
      if (SE10_0 == 0.0 OR u0_0 <= 0.0) {
        sys0_0 = 0.0;
      }
      else{
        if (u0_0 <= A0_0) {
          sys0_0 = 0.0;
        }
        else{
          sys0_0 = divmacro(B0_0*sqr(u0_0-A0_0),"B*(u-A)^2",u0_0,"u");
        }
      }
    /* Output section */
    PopContext()
    return sys0_0;
  }}
/* DSblock C-code: */

#define NX_    5
#define NX2_   2
#define NU_    3
#define NY_    3
#define NW_    151
#define NP_    90
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   3
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1722975506
#define NHash2_ 1169008508
#define NHash3_ 0
#define NI_    0
#define NRelF_ 5
#define NRel_  5
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    17
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 2
#define MAXAux 2
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 189
#define NGlobalHelpI_ 49
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Mostar.Models.AVR_IGLim_Capacitive.Generator_fmu";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/meagh/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
DYMOLA_STATIC const char*GUIDString="{9d11105b-24c8-4af9-808c-7d278686542e}";
DYMOLA_STATIC const double cvodeTolerance=1E-05;
#define FMIStateValueReferencesDef_ 1
DYMOLA_STATIC unsigned int FMIStateValueReferences_[5]={
33554432, 33554433, 33554434, 33554435, 33554436};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,1) = false;
DYNX(W_,2) = false;
DYNX(W_,4) = false;
DYNX(W_,5) = false;
DYNX(W_,6) = false;
DYNX(W_,8) = true;
DYNX(W_,10) = true;
DYNX(W_,11) = true;
DYNX(W_,20) = true;
DYNX(W_,21) = false;
DYNX(W_,23) = false;
DYNX(W_,25) = true;
DYNX(W_,27) = true;
DYNX(W_,29) = true;
DYNX(W_,31) = true;
DYNX(W_,32) = false;
DYNX(W_,77) = 0.0;
DYNX(W_,112) = true;
DYNX(W_,113) = false;
DYNX(W_,115) = false;
DYNX(W_,116) = true;
DYNX(W_,117) = true;
DYNX(W_,119) = true;
DYNX(W_,121) = true;
DYNX(W_,122) = false;
DYNX(W_,125) = 0.7;
DYNX(W_,126) = 1;
DYNX(W_,147) = 0;
DYNX(W_,148) = 0;
DYNX(W_,15) = 0;
DYNX(W_,146) = 1;
DYNX(W_,14) = 0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,0) = DYNX(DP_,0);
DYNX(W_,3) = DYNX(DP_,1);
DYNX(W_,7) = DYNX(DP_,16);
DYNX(W_,9) = DYNX(DP_,17);
DYNX(W_,19) = DYNX(DP_,0);
DYNX(W_,22) = DYNX(DP_,1);
DYNX(W_,24) = DYNX(DP_,18);
DYNX(W_,26) = DYNX(DP_,19);
DYNX(W_,28) = DYNX(DP_,16);
DYNX(W_,30) = DYNX(DP_,17);
DYNX(W_,33) = DYNX(DP_,10);
DYNX(W_,34) = DYNX(DP_,11);
DYNX(W_,35) = DYNX(DP_,12);
DYNX(W_,36) = DYNX(DP_,4);
DYNX(W_,37) = DYNX(DP_,5);
DYNX(W_,38) = DYNX(DP_,2);
DYNX(W_,39) = DYNX(DP_,9);
DYNX(W_,40) = DYNX(DP_,6);
DYNX(W_,41) = DYNX(DP_,7);
DYNX(W_,42) = DYNX(DP_,8);
DYNX(W_,43) = DYNX(DP_,13);
DYNX(W_,44) = DYNX(DP_,14);
DYNX(W_,45) = DYNX(DP_,15);
DYNX(W_,46) = DYNX(DP_,3);
DYNX(W_,60) = 6.283185307179586*DYNX(W_,22);
DYNX(W_,61) = divmacro(DYNX(DP_,69),"Gen1.M_b",DYNX(W_,19),"Gen1.S_b");
DYNX(DYNhelp,0) = cos(DYNX(W_,30));
DYNX(W_,62) = DYNX(W_,28)*DYNX(DYNhelp,0);
DYNX(DYNhelp,1) = sin(DYNX(W_,30));
DYNX(W_,63) = DYNX(W_,28)*DYNX(DYNhelp,1);
DYNX(W_,66) = divmacro(DYNX(W_,24),"Gen1.P_0",DYNX(DP_,69),"Gen1.M_b");
DYNX(W_,67) = divmacro(DYNX(W_,26),"Gen1.Q_0",DYNX(DP_,69),"Gen1.M_b");
DYNX(W_,64) =  -divmacro(DYNX(W_,61)*(DYNX(W_,66)*DYNX(W_,62)+DYNX(W_,67)*
  DYNX(W_,63)),"Gen1.CoB*(Gen1.p0*Gen1.vr0+Gen1.q0*Gen1.vi0)",sqr(DYNX(W_,62))+
  sqr(DYNX(W_,63)),"Gen1.vr0^2+Gen1.vi0^2");
DYNX(W_,65) =  -divmacro(DYNX(W_,61)*(DYNX(W_,66)*DYNX(W_,63)-DYNX(W_,67)*
  DYNX(W_,62)),"Gen1.CoB*(Gen1.p0*Gen1.vi0-Gen1.q0*Gen1.vr0)",sqr(DYNX(W_,62))+
  sqr(DYNX(W_,63)),"Gen1.vr0^2+Gen1.vi0^2");
DYNX(W_,71) = DYNX(W_,46);
DYNX(W_,72) = DYNX(W_,41);
DYNX(W_,84) = DYNX(W_,66);
DYNX(W_,82) = DYNX(W_,28)*DYNX(DYNhelp,0);
DYNX(W_,85) = DYNX(W_,67);
DYNX(W_,83) = DYNX(W_,28)*DYNX(DYNhelp,1);
DYNX(W_,86) = divmacro(DYNX(W_,84)*DYNX(W_,82)+DYNX(W_,85)*DYNX(W_,83),
  "Gen1.S.re*Gen1.VT.re+Gen1.S.im*Gen1.VT.im",DYNX(W_,82)*DYNX(W_,82)+
  DYNX(W_,83)*DYNX(W_,83),"Gen1.VT.re*Gen1.VT.re+Gen1.VT.im*Gen1.VT.im");
DYNX(W_,73) = DYNX(W_,86)+divmacro(DYNX(W_,82)*DYNX(W_,71)+DYNX(W_,83)*
  DYNX(W_,72),"Gen1.VT.re*Gen1.Zs.re+Gen1.VT.im*Gen1.Zs.im",DYNX(W_,71)*
  DYNX(W_,71)+DYNX(W_,72)*DYNX(W_,72),"Gen1.Zs.re*Gen1.Zs.re+Gen1.Zs.im*Gen1.Zs.im");
DYNX(W_,87) =  -divmacro(DYNX(W_,85)*DYNX(W_,82)-DYNX(W_,84)*DYNX(W_,83),
  "Gen1.S.im*Gen1.VT.re-Gen1.S.re*Gen1.VT.im",DYNX(W_,82)*DYNX(W_,82)+
  DYNX(W_,83)*DYNX(W_,83),"Gen1.VT.re*Gen1.VT.re+Gen1.VT.im*Gen1.VT.im");
DYNX(W_,74) = DYNX(W_,87)+divmacro(DYNX(W_,83)*DYNX(W_,71)-DYNX(W_,82)*
  DYNX(W_,72),"Gen1.VT.im*Gen1.Zs.re-Gen1.VT.re*Gen1.Zs.im",DYNX(W_,71)*
  DYNX(W_,71)+DYNX(W_,72)*DYNX(W_,72),"Gen1.Zs.re*Gen1.Zs.re+Gen1.Zs.im*Gen1.Zs.im");
DYNX(W_,75) = DYNX(W_,71)*DYNX(W_,73)-DYNX(W_,72)*DYNX(W_,74);
DYNX(W_,76) = DYNX(W_,71)*DYNX(W_,74)+DYNX(W_,72)*DYNX(W_,73);
DYNX(W_,78) = DYNX(W_,39)-DYNX(W_,41);
DYNX(W_,79) = DYNX(W_,75)+DYNX(W_,77)*DYNX(W_,86)-DYNX(W_,78)*DYNX(W_,87);
DYNX(W_,80) = DYNX(W_,76)+DYNX(W_,77)*DYNX(W_,87)+DYNX(W_,78)*DYNX(W_,86);
DYNX(W_,81) = (PushModelContext(1,"Modelica.Math.atan3(Gen1.Epqp.im, Gen1.Epqp.re, 0)")
  Modelica_Math_atan3(DYNX(W_,80), DYNX(W_,79), 0));
PopModelContext();
DYNX(W_,88) = cos(DYNX(W_,81));
DYNX(DYNhelp,2) = sin(DYNX(W_,81));
DYNX(W_,89) =  -DYNX(DYNhelp,2);
DYNX(W_,90) = DYNX(W_,86)*DYNX(W_,88)-DYNX(W_,87)*DYNX(W_,89);
DYNX(W_,91) =  -(DYNX(W_,86)*DYNX(W_,89)+DYNX(W_,87)*DYNX(W_,88));
DYNX(W_,92) = DYNX(W_,90);
DYNX(W_,93) = DYNX(W_,91);
DYNX(DYNhelp,3) = cos(1.5707963267948966+DYNX(W_,30)-DYNX(W_,81));
DYNX(W_,94) = DYNX(W_,28)*DYNX(DYNhelp,3);
DYNX(DYNhelp,4) = sin(1.5707963267948966+DYNX(W_,30)-DYNX(W_,81));
DYNX(W_,95) = DYNX(W_,28)*DYNX(DYNhelp,4);
DYNX(W_,96) = DYNX(W_,75)*DYNX(W_,88)-DYNX(W_,76)*DYNX(W_,89);
DYNX(W_,97) = DYNX(W_,75)*DYNX(W_,89)+DYNX(W_,76)*DYNX(W_,88);
DYNX(W_,98) =  -DYNX(W_,97);
DYNX(W_,99) = DYNX(W_,96);
DYNX(W_,109) = divmacro(DYNX(W_,41)-DYNX(W_,43),"Gen1.Xppd-Gen1.Xl",DYNX(W_,40)-
  DYNX(W_,43),"Gen1.Xpd-Gen1.Xl");
DYNX(W_,110) = divmacro(DYNX(W_,40)-DYNX(W_,41),"Gen1.Xpd-Gen1.Xppd",DYNX(W_,40)
  -DYNX(W_,43),"Gen1.Xpd-Gen1.Xl");
DYNX(W_,100) = divmacro(DYNX(W_,99)-(DYNX(W_,40)-DYNX(W_,43))*DYNX(W_,109)*
  DYNX(W_,93),"Gen1.PSIppd0-(Gen1.Xpd-Gen1.Xl)*Gen1.K3d*Gen1.id0",DYNX(W_,109)+
  DYNX(W_,110),"Gen1.K3d+Gen1.K4d");
DYNX(W_,101) = DYNX(W_,99)-DYNX(W_,41)*DYNX(W_,93);
DYNX(W_,102) =  -(DYNX(W_,98)+DYNX(W_,42)*DYNX(W_,92));
DYNX(W_,103) = DYNX(W_,95)+DYNX(W_,40)*DYNX(W_,93)+DYNX(W_,46)*DYNX(W_,92);
DYNX(W_,104) = (PushModelContext(1,"OpenIPSL.NonElectrical.Functions.SE(Gen1.Epq0, Gen1.S10, Gen1.S12, 1, 1.2)")
  OpenIPSL_NonElectrical_Functions_SE(DYNX(W_,103), DYNX(W_,44), DYNX(W_,45), 1,
   1.2));
PopModelContext();
DYNX(W_,105) = DYNX(W_,103)*(1+DYNX(W_,104))+(DYNX(W_,38)-DYNX(W_,40))*
  DYNX(W_,93);
DYNX(W_,106) = DYNX(W_,66)+DYNX(W_,46)*DYNX(W_,92)*DYNX(W_,92)+DYNX(W_,46)*
  DYNX(W_,93)*DYNX(W_,93);
DYNX(W_,107) = divmacro((DYNX(W_,40)-DYNX(W_,41))*(DYNX(W_,38)-DYNX(W_,40)),
  "(Gen1.Xpd-Gen1.Xppd)*(Gen1.Xd-Gen1.Xpd)",sqr(DYNX(W_,40)-DYNX(W_,43)),
  "(Gen1.Xpd-Gen1.Xl)^2");
DYNX(W_,108) = divmacro((DYNX(W_,40)-DYNX(W_,43))*(DYNX(W_,41)-DYNX(W_,43)),
  "(Gen1.Xpd-Gen1.Xl)*(Gen1.Xppd-Gen1.Xl)",DYNX(W_,40)-DYNX(W_,41),
  "Gen1.Xpd-Gen1.Xppd");
DYNX(W_,111) = DYNX(DP_,0);
DYNX(W_,114) = DYNX(DP_,1);
DYNX(W_,118) = DYNX(DP_,16);
DYNX(W_,120) = DYNX(DP_,17);
DYNX(W_,123) = DYNX(DP_,72);
DYNX(W_,124) = DYNX(DP_,73);
DYNX(W_,133) = divmacro(DYNX(DP_,75)*DYNX(W_,118)+DYNX(DP_,77)*sqr(DYNX(W_,118))
  +DYNX(W_,123),"constantLoad.S_i.re*constantLoad.v_0+constantLoad.S_y.re*constantLoad.v_0^2+constantLoad.S_p.re",
  DYNX(W_,111),"constantLoad.S_b");
DYNX(W_,134) = divmacro(DYNX(DP_,76)*DYNX(W_,118)+DYNX(DP_,78)*sqr(DYNX(W_,118))
  +DYNX(W_,124),"constantLoad.S_i.im*constantLoad.v_0+constantLoad.S_y.im*constantLoad.v_0^2+constantLoad.S_p.im",
  DYNX(W_,111),"constantLoad.S_b");
DYNX(DYNhelp,5) = cos(DYNX(W_,120));
DYNX(W_,135) = DYNX(W_,118)*DYNX(DYNhelp,5);
DYNX(DYNhelp,6) = sin(DYNX(W_,120));
DYNX(W_,136) = DYNX(W_,118)*DYNX(DYNhelp,6);
DYNX(W_,137) = divmacro(DYNX(W_,133)*DYNX(W_,135)+DYNX(W_,134)*DYNX(W_,136),
  "constantLoad.p0*constantLoad.vr0+constantLoad.q0*constantLoad.vi0",sqr(
  DYNX(W_,135))+sqr(DYNX(W_,136)),"constantLoad.vr0^2+constantLoad.vi0^2");
DYNX(W_,138) = divmacro(DYNX(W_,133)*DYNX(W_,136)-DYNX(W_,134)*DYNX(W_,135),
  "constantLoad.p0*constantLoad.vi0-constantLoad.q0*constantLoad.vr0",sqr(
  DYNX(W_,135))+sqr(DYNX(W_,136)),"constantLoad.vr0^2+constantLoad.vi0^2");
DYNX(W_,139) = divmacro((1-(DYNX(DP_,79)+DYNX(DP_,81)))*DYNX(W_,123)*
  DYNX(W_,111),"(1-(constantLoad.a.re+constantLoad.b.re))*constantLoad.S_p.re*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,140) = divmacro((1-(DYNX(DP_,80)+DYNX(DP_,82)))*DYNX(W_,124)*
  DYNX(W_,111),"(1-(constantLoad.a.im+constantLoad.b.im))*constantLoad.S_p.im*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,141) = divmacro((DYNX(DP_,75)+divmacro(DYNX(DP_,79)*DYNX(W_,123),
  "constantLoad.a.re*constantLoad.S_p.re",DYNX(W_,118),"constantLoad.v_0"))*
  DYNX(W_,111),"(constantLoad.S_i.re+constantLoad.a.re*constantLoad.S_p.re/constantLoad.v_0)*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,142) = divmacro((DYNX(DP_,76)+divmacro(DYNX(DP_,80)*DYNX(W_,124),
  "constantLoad.a.im*constantLoad.S_p.im",DYNX(W_,118),"constantLoad.v_0"))*
  DYNX(W_,111),"(constantLoad.S_i.im+constantLoad.a.im*constantLoad.S_p.im/constantLoad.v_0)*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,143) = divmacro((DYNX(DP_,77)+divmacro(DYNX(DP_,81)*DYNX(W_,123),
  "constantLoad.b.re*constantLoad.S_p.re",sqr(DYNX(W_,118)),"constantLoad.v_0^2"))
  *DYNX(W_,111),"(constantLoad.S_y.re+constantLoad.b.re*constantLoad.S_p.re/constantLoad.v_0^2)*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,144) = divmacro((DYNX(DP_,78)+divmacro(DYNX(DP_,82)*DYNX(W_,124),
  "constantLoad.b.im*constantLoad.S_p.im",sqr(DYNX(W_,118)),"constantLoad.v_0^2"))
  *DYNX(W_,111),"(constantLoad.S_y.im+constantLoad.b.im*constantLoad.S_p.im/constantLoad.v_0^2)*constantLoad.S_b",
  DYNX(W_,111)*DYNX(W_,111),"constantLoad.S_b*constantLoad.S_b");
DYNX(W_,149) = IF DYNX(W_,134) <= 1E-15 THEN 1 ELSE divmacro(DYNX(W_,133),
  "constantLoad.p0",DYNX(W_,134),"constantLoad.q0");
DYNX(W_,150) = divmacro(DYNX(W_,133)+DYNX(DP_,89),"constantLoad.p0+constantLoad.d_P",
  DYNX(W_,149),"constantLoad.PF")-DYNX(W_,134);
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,145) = 1;
#endif
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,12) = DYNX(W_,7)*cos(DYNX(W_,9));
DYNX(W_,13) = DYNX(W_,7)*sin(DYNX(W_,9));
DYNX(W_,16) = DYNX(W_,7);
DYNX(W_,17) = DYNX(W_,9);
DYNX(W_,47) = DYNX(W_,64);
DYNX(W_,48) = DYNX(W_,65);
DYNX(W_,49) = DYNX(W_,66);
DYNX(W_,50) = DYNX(W_,30);
DYNX(W_,51) = sqrtGuarded(sqr(DYNX(W_,64))+sqr(DYNX(W_,65)),"Gen1.ir0^2+Gen1.ii0^2");
DYNX(W_,52) = atan2(DYNX(W_,65), DYNX(W_,64));
DYNX(W_,53) = divmacro(DYNX(W_,24),"Gen1.P_0",DYNX(W_,19),"Gen1.S_b");
DYNX(W_,54) = divmacro(DYNX(W_,26),"Gen1.Q_0",DYNX(W_,19),"Gen1.S_b");
DYNX(W_,55) = DYNX(W_,106);
DYNX(W_,56) = DYNX(W_,93);
DYNX(W_,57) = DYNX(W_,92);
DYNX(W_,58) = DYNX(W_,94);
DYNX(W_,59) = DYNX(W_,95);
DYNX(W_,68) = DYNX(W_,99);
DYNX(W_,69) = DYNX(W_,101);
DYNX(W_,70) = DYNX(W_,102);
DYNX(W_,129) = DYNX(W_,120);
DYNX(W_,130) = DYNX(W_,118);
DYNX(W_,128) = DYNX(W_,138);
DYNX(W_,127) = DYNX(W_,137);
DYNX(X_,0) = DYNX(DP_,70);
DYNX(X_,1) = DYNX(W_,81);
DYNX(X_,2) = DYNX(W_,103);
DYNX(X_,3) = DYNX(W_,100);
DYNX(X_,4) = DYNX(W_,98);
DYNX(Y_,0) = DYNX(W_,28);
DYNX(Y_,1) = DYNX(W_,105);
DYNX(Y_,2) = DYNX(W_,81);
DYNX(U_,0) = DYNX(W_,105);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,4) = 0;
DYNX(F_,2) = 0;
DYNX(F_,3) = 0;
DYNX(X_,1) = DYNX(W_,81);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 2 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,7) = divmacro(1.0,"1.0",DYNX(W_,33),"Gen1.Tpd0");
DYNX(Y_,1) = DYNX(W_,105);
SolveScalarLinearParametric( -DYNX(DYNhelp,7)*(-1.0)," -(-1.0)/Gen1.Tpd0", 
  DYNX(DYNhelp,7)*DYNX(U_,0),"EFD1/Gen1.Tpd0", DYNX(Y_,1),"XadIfd");
 /* End of Equation Block */ 


{ /* Non-linear system of equations to solve. */
/* Tag: initialization.nonlinear[1] */
/* Introducing 9 common subexpressions used in 10 expressions */
/* Of the common subexpressions 8 are reals, 0 are integers, and 1
   are booleans. */
const char*const varnames_[]={"Gen1.iq", "Gen1.id", "Gen1.PSIkd"};
const double nominal_[]={1, 1, 1};
NonLinearSystemOfEquations(Jacobian__, residue__, x__, 3, 0, 1, 1, -2, 
  DYNX(DYNhelp,8), 74, DYNX(did_->helpvari_vec,0), 25);
SetInitVector(x__, 1, DYNX(W_,57), DYNX(W_,92));
SetInitVector(x__, 2, DYNX(W_,56), DYNX(W_,93));
SetInitVector(x__, 3, DYNX(X_,3), DYNX(W_,100));
Residues;
  DYNX(DYNhelp,82) = cos(DYNX(X_,1));
  DYNX(DYNhelp,83) = DYNX(W_,61)*DYNX(DYNhelp,82);
  DYNX(DYNhelp,84) = sin(DYNX(X_,1));
  DYNX(DYNhelp,85) = DYNX(W_,61)*DYNX(DYNhelp,84);
  DYNX(W_,48) = DYNX(DYNhelp,83)*DYNX(W_,56)-DYNX(DYNhelp,85)*DYNX(W_,57);
  DYNX(W_,47) =  -(DYNX(DYNhelp,85)*DYNX(W_,56)+DYNX(DYNhelp,83)*DYNX(W_,57));
  DYNX(DYNhelp,86) = (DYNX(W_,40)-DYNX(W_,43))*DYNX(W_,56);
  DYNX(DYNhelp,87) = divmacro(1.0,"1.0",DYNX(W_,34),"Gen1.Tppd0");
  DYNX(X_,2) = DYNX(DYNhelp,87)*(DYNX(X_,3)+DYNX(DYNhelp,86))*DYNX(W_,34);
  DYNX(W_,68) = DYNX(X_,2)*DYNX(W_,109)+DYNX(X_,3)*DYNX(W_,110);
  DYNX(W_,69) = DYNX(W_,68)-DYNX(W_,41)*DYNX(W_,56);
  DYNX(W_,59) = DYNX(W_,69)-DYNX(W_,46)*DYNX(W_,57);
  DYNX(DYNhelp,88) = divmacro(1.0,"1.0",DYNX(W_,35),"Gen1.Tppq0");
  DYNX(X_,4) = DYNX(DYNhelp,88)*(DYNX(W_,39)-DYNX(W_,42))*DYNX(W_,57)*
    DYNX(W_,35);
  DYNX(W_,70) =  -(DYNX(X_,4)+DYNX(W_,42)*DYNX(W_,57));
  DYNX(W_,58) =  -(DYNX(W_,70)+DYNX(W_,46)*DYNX(W_,56));
  DYNX(W_,13) = DYNX(DYNhelp,84)*DYNX(W_,59)-DYNX(DYNhelp,82)*DYNX(W_,58);
  DYNX(W_,12) = DYNX(DYNhelp,84)*DYNX(W_,58)+DYNX(DYNhelp,82)*DYNX(W_,59);
  DYNX(W_,130) = sqrtGuarded(sqr(DYNX(W_,12))+sqr(DYNX(W_,13)),"bus.p.vr^2+bus.p.vi^2");
  DYNX(W_,145) = IF Less(DYNX(W_,130),"constantLoad.v", 0.35,"0.35", 0) AND 
    Greater(DYNX(W_,130),"constantLoad.v", 0,"0", 1) THEN 2*sqr(1.4285714285714286
    *DYNX(W_,130)) ELSE IF Greater(DYNX(W_,130),"constantLoad.v", 0.35,"0.35", 2)
     AND Less(DYNX(W_,130),"constantLoad.v", 0.7,"0.7", 3) THEN 1-2*sqr(
    1.4285714285714286*(DYNX(W_,130)-0.7)) ELSE 1;
DYNX(DYNhelp,89) = DYNX(X_,2)-DYNX(X_,3);
DYNX(DYNhelp,90) = GreaterEqualTime(0, 0) AND LessEqual(DYNTime,"time", 0,"0", 4);
SetVector(residue__, 1, DYNX(Y_,1)-(DYNX(W_,107)*(DYNX(DYNhelp,89)-
  DYNX(DYNhelp,86))+(DYNX(W_,38)-DYNX(W_,40))*DYNX(W_,56)+((PushModelContext(1,
  "OpenIPSL.NonElectrical.Functions.SE(Gen1.Epq, Gen1.S10, Gen1.S12, 1, 1.2)")
  OpenIPSL_NonElectrical_Functions_SE(DYNX(X_,2), DYNX(W_,44), DYNX(W_,45), 1, 
  1.2))+1)*DYNX(X_,2)));
PopModelContext();
SetVector(residue__, 2, IF DYNX(DYNhelp,90) THEN DYNX(W_,141)*DYNX(W_,130)+
  DYNX(W_,143)*sqr(DYNX(W_,130))+DYNX(W_,145)*(DYNX(W_,139)+DYNX(DP_,89))+
  DYNX(U_,1)+DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48) ELSE DYNX(W_,141)*
  DYNX(W_,130)+DYNX(W_,143)*sqr(DYNX(W_,130))+DYNX(W_,145)*DYNX(W_,139)+
  DYNX(U_,1)+DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48));
SetVector(residue__, 3, IF DYNX(DYNhelp,90) THEN DYNX(W_,142)*DYNX(W_,130)+
  DYNX(W_,144)*sqr(DYNX(W_,130))+DYNX(W_,145)*(DYNX(W_,140)+DYNX(W_,150))+
  DYNX(U_,2)+DYNX(W_,13)*DYNX(W_,47)-DYNX(W_,12)*DYNX(W_,48) ELSE DYNX(W_,142)*
  DYNX(W_,130)+DYNX(W_,144)*sqr(DYNX(W_,130))+DYNX(W_,145)*DYNX(W_,140)+
  DYNX(U_,2)+DYNX(W_,13)*DYNX(W_,47)-DYNX(W_,12)*DYNX(W_,48));

{ /* No analytic Jacobian available*/
SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[1]");
DYNX(W_,57) = GetVector(x__, 1);
DYNX(W_,56) = GetVector(x__, 2);
DYNX(X_,3) = GetVector(x__, 3);
EndNonLinearSystemOfEquationsInit(residue__, x__, 1);
 /* End of Non-Linear Equation Block */ }



DYNX(X_,0) = DYNX(DP_,70);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,68) = DYNX(X_,2)*DYNX(W_,109)+DYNX(X_,3)*DYNX(W_,110);
DYNX(Y_,2) = DYNX(X_,1);

if (Init_ || DYNTime==InitTime) {
DYNX(Aux_,0) = Less(DYNX(W_,130),"constantLoad.v", 0.35,"0.35", 0) AND Greater(\
DYNX(W_,130),"constantLoad.v", 0,"0", 1);}
if (Init_ || DYNTime==InitTime) {
DYNX(Aux_,1) = IF  NOT DYNX(Aux_,0) THEN Greater(DYNX(W_,130),"constantLoad.v", \
0.35,"0.35", 2) AND Less(DYNX(W_,130),"constantLoad.v", 0.7,"0.7", 3) ELSE false;}
MixedSystemOfEquations(12, DYNX(DYNhelp,91))

  { /* Non-linear system of equations to solve. */
  /* Tag: simulation.nonlinear[1] */
  /* Introducing 68 common subexpressions and reusing 1 variables totally
     used in 45 expressions */
  /* Of the common subexpressions 68 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"Gen1.id", "Gen1.iq"};
  const double nominal_[]={1, 1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 2, 0, 0, 2, 4, 
    DYNX(DYNhelp,103), 53, DYNX(did_->helpvari_vec,25), 24);
  SetInitVector(x__, 1, DYNX(W_,56), Remember_(DYNX(W_,56), 0));
  SetInitVector(x__, 2, DYNX(W_,57), Remember_(DYNX(W_,57), 1));
  Residues;
    DYNX(W_,69) = DYNX(W_,68)-DYNX(W_,41)*DYNX(W_,56);
    DYNX(DYNhelp,156) = cos(DYNX(X_,1));
    DYNX(DYNhelp,157) = DYNX(W_,61)*DYNX(DYNhelp,156);
    DYNX(DYNhelp,158) = sin(DYNX(X_,1));
    DYNX(DYNhelp,159) = DYNX(W_,61)*DYNX(DYNhelp,158);
    DYNX(W_,48) = DYNX(DYNhelp,157)*DYNX(W_,56)-DYNX(DYNhelp,159)*DYNX(W_,57);
    DYNX(W_,70) =  -(DYNX(X_,4)+DYNX(W_,42)*DYNX(W_,57));
    DYNX(W_,58) =  -(DYNX(W_,70)+DYNX(W_,46)*DYNX(W_,56));
    DYNX(W_,59) = DYNX(W_,69)-DYNX(W_,46)*DYNX(W_,57);
    DYNX(W_,12) = DYNX(DYNhelp,158)*DYNX(W_,58)+DYNX(DYNhelp,156)*DYNX(W_,59);
    DYNX(W_,47) =  -(DYNX(DYNhelp,159)*DYNX(W_,56)+DYNX(DYNhelp,157)*DYNX(W_,57));
    DYNX(W_,13) = DYNX(DYNhelp,158)*DYNX(W_,59)-DYNX(DYNhelp,156)*DYNX(W_,58);
    DYNX(W_,130) = sqrtGuarded(sqr(DYNX(W_,12))+sqr(DYNX(W_,13)),
      "bus.p.vr^2+bus.p.vi^2");
    DYNX(W_,145) = IF DYNX(Aux_,0) THEN 2*sqr(1.4285714285714286*DYNX(W_,130))
       ELSE IF DYNX(Aux_,1) THEN 1-2*sqr(1.4285714285714286*(DYNX(W_,130)-0.7))
       ELSE 1;
  DYNX(DYNhelp,160) = GreaterEqualTime(0, 0) AND LessEqual(DYNTime,"time", 0,"0",
     4);
  SetVector(residue__, 1, IF DYNX(DYNhelp,160) THEN DYNX(W_,141)*DYNX(W_,130)+
    DYNX(W_,143)*sqr(DYNX(W_,130))+DYNX(W_,145)*(DYNX(W_,139)+DYNX(DP_,89))+
    DYNX(U_,1)+DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48) ELSE DYNX(W_,141)
    *DYNX(W_,130)+DYNX(W_,143)*sqr(DYNX(W_,130))+DYNX(W_,145)*DYNX(W_,139)+
    DYNX(U_,1)+DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48));
  SetVector(residue__, 2, IF DYNX(DYNhelp,160) THEN DYNX(W_,142)*DYNX(W_,130)+
    DYNX(W_,144)*sqr(DYNX(W_,130))+DYNX(W_,145)*(DYNX(W_,140)+DYNX(W_,150))+
    DYNX(U_,2)+DYNX(W_,13)*DYNX(W_,47)-DYNX(W_,12)*DYNX(W_,48) ELSE DYNX(W_,142)
    *DYNX(W_,130)+DYNX(W_,144)*sqr(DYNX(W_,130))+DYNX(W_,145)*DYNX(W_,140)+
    DYNX(U_,2)+DYNX(W_,13)*DYNX(W_,47)-DYNX(W_,12)*DYNX(W_,48));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  DYNX(DYNhelp,161) = DYNX(W_,13)*DYNX(DYNhelp,157);
  DYNX(DYNhelp,162) = 2.0*DYNX(W_,143)*DYNX(W_,130);
  DYNX(DYNhelp,163) = IF DYNX(Aux_,0) THEN 8.16326530612245*DYNX(W_,130) ELSE 
    IF DYNX(Aux_,1) THEN (-8.16326530612245)*(DYNX(W_,130)-0.7) ELSE 0.0;
  DYNX(DYNhelp,164) = DYNX(W_,141)+DYNX(DYNhelp,162)+DYNX(DYNhelp,163)*(IF 
    DYNX(DYNhelp,160) THEN DYNX(W_,139)+DYNX(DP_,89) ELSE DYNX(W_,139));
  DYNX(DYNhelp,165) = divmacro(1.0,"1.0",DYNX(W_,130),"sqrt(bus.p.vr^2+bus.p.vi^2)");
  DYNX(DYNhelp,166) = DYNX(W_,47)+DYNX(DYNhelp,165)*DYNX(W_,12)*DYNX(DYNhelp,164);
  DYNX(DYNhelp,167) = DYNX(DYNhelp,156)*DYNX(DYNhelp,166);
  DYNX(DYNhelp,168) = DYNX(W_,48)+DYNX(DYNhelp,165)*DYNX(W_,13)*DYNX(DYNhelp,164);
  DYNX(DYNhelp,169) = DYNX(DYNhelp,158)*DYNX(DYNhelp,168);
  DYNX(DYNhelp,170) = DYNX(DYNhelp,167)+DYNX(DYNhelp,169);
  DYNX(DYNhelp,171) = DYNX(DYNhelp,158)*DYNX(DYNhelp,166)-DYNX(DYNhelp,156)*
    DYNX(DYNhelp,168);
  DYNX(DYNhelp,172) = DYNX(W_,12)*DYNX(DYNhelp,159);
  DYNX(DYNhelp,173) = DYNX(W_,13)*DYNX(DYNhelp,159);
  DYNX(DYNhelp,174) = DYNX(W_,12)*DYNX(DYNhelp,157);
  DYNX(DYNhelp,175) = 2.0*DYNX(W_,144)*DYNX(W_,130);
  DYNX(DYNhelp,176) = DYNX(W_,142)+DYNX(DYNhelp,175)+DYNX(DYNhelp,163)*(IF 
    DYNX(DYNhelp,160) THEN DYNX(W_,140)+DYNX(W_,150) ELSE DYNX(W_,140));
  DYNX(DYNhelp,177) = DYNX(DYNhelp,165)*DYNX(W_,12)*DYNX(DYNhelp,176)-
    DYNX(W_,48);
  DYNX(DYNhelp,178) = DYNX(DYNhelp,156)*DYNX(DYNhelp,177);
  DYNX(DYNhelp,179) = DYNX(W_,47)+DYNX(DYNhelp,165)*DYNX(W_,13)*DYNX(DYNhelp,176);
  DYNX(DYNhelp,180) = DYNX(DYNhelp,158)*DYNX(DYNhelp,179);
  DYNX(DYNhelp,181) = DYNX(DYNhelp,178)+DYNX(DYNhelp,180);
  DYNX(DYNhelp,182) = DYNX(DYNhelp,158)*DYNX(DYNhelp,177)-DYNX(DYNhelp,156)*
    DYNX(DYNhelp,179);
  SetMatrixLeading(Jacobian__, 1, 1, 2, DYNX(DYNhelp,161)-DYNX(DYNhelp,170)*
    DYNX(W_,41)-DYNX(DYNhelp,171)*DYNX(W_,46)-DYNX(DYNhelp,172));
  SetMatrixLeading(Jacobian__, 1, 2, 2, DYNX(DYNhelp,171)*DYNX(W_,42)-
    DYNX(DYNhelp,173)-DYNX(DYNhelp,170)*DYNX(W_,46)-DYNX(DYNhelp,174));
  SetMatrixLeading(Jacobian__, 2, 1, 2,  -(DYNX(DYNhelp,181)*DYNX(W_,41)+
    DYNX(DYNhelp,174)+DYNX(DYNhelp,182)*DYNX(W_,46)+DYNX(DYNhelp,173)));
  SetMatrixLeading(Jacobian__, 2, 2, 2, DYNX(DYNhelp,172)+DYNX(DYNhelp,182)*
    DYNX(W_,42)-DYNX(DYNhelp,181)*DYNX(W_,46)-DYNX(DYNhelp,161));

  SolveNonLinearSystemOfEquationsMixed(Jacobian__, 0, 0, 0, residue__, x__,"Tag: simulation.nonlinear[1]");
  DYNX(W_,56) = GetVector(x__, 1);
  DYNX(W_,57) = GetVector(x__, 2);
  EndNonLinearSystemOfEquations(residue__, x__);
   /* End of Non-Linear Equation Block */ }




  MixedModeStartBoolean
  UpdateVariableNamed(DYNX(Aux_,0),"discreteexpr_0.", Less(DYNX(W_,130),
    "constantLoad.v", 0.35,"0.35", 0) AND Greater(DYNX(W_,130),"constantLoad.v",
     0,"0", 1));
  UpdateVariableNamed(DYNX(Aux_,1),"discreteexpr_1.", IF  NOT DYNX(Aux_,0) THEN 
    Greater(DYNX(W_,130),"constantLoad.v", 0.35,"0.35", 2) AND Less(DYNX(W_,130),
    "constantLoad.v", 0.7,"0.7", 3) ELSE false);
  MixedModeInit(4, DYNX(DYNhelp,183))
  ThetaMixedCross(0,0)
  ThetaMixedCross(1,1)
  ThetaMixedCross(2,2)
  ThetaMixedCross(3,3)
  MixedModeEndBoolean
  UpdateReal(DYNX(W_,70), 1)
  UpdateReal(DYNX(W_,69), 2)
  UpdateReal(DYNX(W_,57), 3)
  UpdateReal(DYNX(W_,48), 4)
  UpdateReal(DYNX(W_,13), 5)
  UpdateReal(DYNX(W_,59), 6)
  UpdateReal(DYNX(W_,58), 7)
  UpdateReal(DYNX(W_,56), 8)
  UpdateReal(DYNX(W_,47), 9)
  UpdateReal(DYNX(W_,145), 10)
  UpdateReal(DYNX(W_,130), 11)
  UpdateReal(DYNX(W_,12), 12)
EndMixedSystemOfEquations

DYNX(Y_,0) = DYNX(W_,130);
DYNX(DYNhelp,187) = DYNX(W_,40)-DYNX(W_,43);
DYNX(DYNhelp,188) = (PushModelContext(1,"OpenIPSL.NonElectrical.Functions.SE(Gen1.Epq, Gen1.S10, Gen1.S12, 1, 1.2)")
  OpenIPSL_NonElectrical_Functions_SE(DYNX(X_,2), DYNX(W_,44), DYNX(W_,45), 1, 
  1.2));
PopModelContext();
DYNX(Y_,1) = DYNX(W_,107)*(DYNX(X_,2)-DYNX(X_,3)-DYNX(DYNhelp,187)*DYNX(W_,56))+
  (DYNX(W_,38)-DYNX(W_,40))*DYNX(W_,56)+(DYNX(DYNhelp,188)+1)*DYNX(X_,2);
DYNX(W_,128) =  -DYNX(W_,48);
DYNX(W_,127) =  -DYNX(W_,47);

DynamicsSection
DYNX(F_,4) = divmacro((DYNX(W_,39)-DYNX(W_,42))*DYNX(W_,57)-DYNX(X_,4),
  "(Gen1.Xq-Gen1.Xppq)*Gen1.iq-Gen1.PSIppq",DYNX(W_,35),"Gen1.Tppq0");
DYNX(W_,55) = DYNX(W_,69)*DYNX(W_,57)-DYNX(W_,70)*DYNX(W_,56);
DYNX(F_,0) = divmacro(divmacro(DYNX(W_,106)-DYNX(W_,37)*DYNX(X_,0),
  "Gen1.pm0-Gen1.D*Gen1.w",DYNX(X_,0)+1,"Gen1.w+1")-DYNX(W_,55),"(Gen1.pm0-Gen1.D*Gen1.w)/(Gen1.w+1)-Gen1.Te",2
  *DYNX(W_,36),"2*Gen1.H");
DYNX(F_,1) = DYNX(W_,60)*DYNX(X_,0);
DYNX(F_,2) = divmacro(DYNX(U_,0)-DYNX(Y_,1),"EFD1-XadIfd",DYNX(W_,33),
  "Gen1.Tpd0");
DYNX(F_,3) = divmacro(DYNX(X_,2)-DYNX(X_,3)-(DYNX(W_,40)-DYNX(W_,43))*
  DYNX(W_,56),"Gen1.Epq-Gen1.PSIkd-(Gen1.Xpd-Gen1.Xl)*Gen1.id",DYNX(W_,34),
  "Gen1.Tppd0");

AcceptedSection1

AcceptedSection2
DYNX(W_,16) = DYNX(W_,130);
DYNX(W_,17) = atan2(DYNX(W_,13), DYNX(W_,12));
DYNX(W_,18) = 57.29577951308232*DYNX(W_,17);
DYNX(W_,53) =  -(DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48));
DYNX(W_,49) = divmacro(DYNX(W_,53),"Gen1.P",DYNX(W_,61),"Gen1.CoB");
DYNX(W_,50) = DYNX(W_,17);
DYNX(W_,51) = sqrtGuarded(sqr(DYNX(W_,48))+sqr(DYNX(W_,47)),"Gen1.p.ii^2+Gen1.p.ir^2");
DYNX(W_,52) = atan2(DYNX(W_,48), DYNX(W_,47));
DYNX(W_,54) = DYNX(W_,12)*DYNX(W_,48)-DYNX(W_,13)*DYNX(W_,47);
DYNX(W_,129) = DYNX(W_,17);
DYNX(W_,131) =  -(DYNX(W_,12)*DYNX(W_,47)+DYNX(W_,13)*DYNX(W_,48));
DYNX(W_,132) = DYNX(W_,12)*DYNX(W_,48)-DYNX(W_,13)*DYNX(W_,47);

DefaultSection
InitialSection
DYNX(Aux_,0) = DYNX(W_,130) < 0.35 AND DYNX(W_,130) > 0;
DYNX(Aux_,1) = IF  NOT DYNX(Aux_,0) THEN DYNX(W_,130) > 0.35 AND DYNX(W_,130) < 
  0.7 ELSE false;
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [VA|MVA]", 0, 30000000, 0.0,0.0,\
100000000.0,0,560)
DeclareParameter("SysData.fn", "System frequency [Hz]", 1, 50, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xd", "[1]", 2, 1.183, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.R_a", "[1]", 3, 0.004799183673469388, \
0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.H", "[s]", 4, 2.137, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.D", "", 5, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xpd", "[1]", 6, 0.371, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xppd", "[1]", 7, 0.215, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xppq", "[1]", 8, 0.241, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xq", "[1]", 9, 0.62, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tpd0", "[s]", 10, 3.77, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tppd0", "[s]", 11, 0.0552, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tppq0", "[s]", 12, 0.0823, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xl", "[1]", 13, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.S10", "[1]", 14, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.S12", "[1]", 15, 0.4, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_0", "[1]", 16, 0.9745, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.A_0", "[rad]", 17, -15, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.P_0", "[W]", 18, 4996435.71, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Q_0", "[var]", 19, -2475000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_R", "", 20, 0.01, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_C1", "", 21, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_B1", "", 22, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_C2", "", 23, 0.02, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_B2", "", 24, 0.005, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_R", "", 25, 500, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_RMAX", "", 26, 4.35, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_RMIN", "", 27, -3.825, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_1_AVR", "", 28, 0.005, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_C", "", 29, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UC1", "", 30, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UB1", "", 31, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UC2", "", 32, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UB2", "", 33, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OC1", "", 34, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OB1", "", 35, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OC2", "", 36, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OB2", "", 37, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w1", "", 38, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w2", "", 39, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_6", "", 40, 1E-09, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w3", "", 41, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w4", "", 42, 1E-09, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_7", "", 43, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S2", "", 44, 0.99, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S3", "", 45, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_8", "", 46, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_9", "", 47, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S1", "", 48, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_1", "", 49, 0.15, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_2", "", 50, 0.025, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_3", "", 51, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_4", "", 52, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_10", "", 53, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_11", "", 54, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S1MAX", "", 55, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S1MIN", "", 56, -0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S2MAX", "", 57, 1.25, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S2MIN", "", 58, -1.25, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_STMAX", "", 59, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_STMIN", "", 60, -0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.M", "[:#(type=Integer)]", 61, 1, 0.0,0.0,0.0,\
0,564)
DeclareParameter("machineData.data.N", "[:#(type=Integer)]", 62, 1, 0.0,0.0,0.0,\
0,564)
DeclareVariable("bus.S_b", "System base power [VA|MVA]", 0.0, 0.0,0.0,\
100000000.0,0,513)
DeclareVariable("bus.enableS_b", "Enable S_b in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("bus.V_b", "Base voltage of the bus [V|kV]", 63, 400000.0, \
0.0,0.0,10000.0,0,560)
DeclareVariable("bus.enableV_b", "Enable V_b in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("bus.fn", "System frequency [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("bus.enablefn", "Enable fn in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("bus.P_0", "Initial active power [W|MW]", 64, 1000000.0, \
0.0,0.0,100000000.0,0,560)
DeclareVariable("bus.enableP_0", "Enable P_0 in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("bus.Q_0", "Initial reactive power [var|MVA]", 65, 0, 0.0,0.0,\
100000000.0,0,560)
DeclareVariable("bus.enableQ_0", "Enable Q_0 in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("bus.v_0", "Initial voltage magnitude [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("bus.enablev_0", "Enable v_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("bus.angle_0", "Initial voltage angle [rad|deg]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("bus.enableangle_0", "Enable angle_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("bus.displayPF", "Display power flow: [:#(type=Boolean)]", 66, \
false, 0.0,0.0,0.0,0,562)
DeclareVariable("bus.enabledisplayPF", "Enable displayPF in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("bus.p.vr", "Real part of the voltage [1]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("bus.p.vi", "Imaginary part of the voltage [1]", 0.0, 0.0,0.0,\
0.0,0,520)
DeclareVariable("bus.p.ir", "Real part of the current [1]", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("bus.p.ii", "Imaginary part of the current [1]", 0, 0.0,0.0,0.0,\
0,777)
DeclareVariable("bus.V", "Bus voltage magnitude [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("bus.angle", "Bus voltage angle [rad|deg]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("bus.angleDisplay", "Angle in degrees for display purposes [deg]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.S_b", "System base power [VA|MVA]", 0.0, 0.0,0.0,\
100000000.0,0,513)
DeclareVariable("Gen1.enableS_b", "Enable S_b in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("Gen1.V_b", "Base voltage of the bus [V|kV]", 67, 400000.0, \
0.0,0.0,10000.0,0,560)
DeclareVariable("Gen1.enableV_b", "Enable V_b in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("Gen1.fn", "System frequency [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.enablefn", "Enable fn in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("Gen1.P_0", "Initial active power [W|MW]", 0.0, 0.0,0.0,\
100000000.0,0,513)
DeclareVariable("Gen1.enableP_0", "Enable P_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("Gen1.Q_0", "Initial reactive power [var|MVA]", 0.0, 0.0,0.0,\
100000000.0,0,513)
DeclareVariable("Gen1.enableQ_0", "Enable Q_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("Gen1.v_0", "Initial voltage magnitude [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.enablev_0", "Enable v_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("Gen1.angle_0", "Initial voltage angle [rad|deg]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Gen1.enableangle_0", "Enable angle_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("Gen1.displayPF", "Display power flow: [:#(type=Boolean)]", 68,\
 false, 0.0,0.0,0.0,0,562)
DeclareVariable("Gen1.enabledisplayPF", "Enable displayPF in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("Gen1.M_b", "Machine base power [VA|MVA]", 69, 30000000, \
0.0,0.0,100000000.0,0,560)
DeclareVariable("Gen1.Tpd0", "d-axis transient open-circuit time constant [s]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Tppd0", "d-axis sub-transient open-circuit time constant [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Tppq0", "q-axis sub-transient open-circuit time constant [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.H", "Inertia constant [s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.D", "Speed damping", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Xd", "d-axis reactance [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Xq", "q-axis reactance [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Xpd", "d-axis transient reactance [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.Xppd", "d-axis sub-transient reactance [1]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Gen1.Xppq", "q-axis sub-transient reactance [1]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Gen1.Xl", "leakage reactance [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Gen1.S10", "Saturation factor at 1.0 pu [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("Gen1.S12", "Saturation factor at 1.2 pu [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("Gen1.R_a", "Armature resistance [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Gen1.w0", "Initial speed deviation from nominal [1]", 70, 0, \
-0.999999999999999,1E+100,0.0,0,560)
DeclareAlias2("Gen1.p.vr", "Real part of the voltage [1]", "bus.p.vr", 1, 5, 12,\
 4)
DeclareAlias2("Gen1.p.vi", "Imaginary part of the voltage [1]", "bus.p.vi", 1, 5,\
 13, 4)
DeclareVariable("Gen1.p.ir", "Real part of the current [1]", 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("Gen1.p.ii", "Imaginary part of the current [1]", 0.0, 0.0,0.0,\
0.0,0,776)
DeclareAlias2("Gen1.SPEED", "Machine speed deviation from nominal [pu] [1]", \
"Gen1.w", 1, 1, 0, 0)
DeclareAlias2("Gen1.PMECH", "Turbine mechanical power (machine base) [1]", \
"Gen1.pm0", 1, 5, 106, 0)
DeclareAlias2("Gen1.PMECH0", "Initial value of machine electrical power (machine base) [1]",\
 "Gen1.pm0", 1, 5, 106, 0)
DeclareAlias2("Gen1.ETERM", "Machine terminal voltage [pu] [1]", "Eterm", 1, 3, 0,\
 0)
DeclareAlias2("Gen1.EFD", "Generator main field voltage [pu] [1]", "EFD1", 1, 2,\
 0, 0)
DeclareAlias2("Gen1.EFD0", "Initial generator main field voltage [pu] [1]", \
"Gen1.efd0", 1, 5, 105, 0)
DeclareVariable("Gen1.PELEC", "Machine electrical power (machine base) [1]", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareAlias2("Gen1.ISORCE", "Machine source current [pu] [1]", "XadIfd", 1, 3, 1,\
 0)
DeclareAlias2("Gen1.ANGLE", "Machine relative rotor angle [rad]", "Gen1.delta", 1,\
 1, 1, 0)
DeclareAlias2("Gen1.XADIFD", "Machine field current [pu] [1]", "XadIfd", 1, 3, 1,\
 0)
DeclareState("Gen1.w", "Machine speed deviation [1]", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("Gen1.der(w)", "der(Machine speed deviation) [s-1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("Gen1.delta", "Rotor angle [rad|deg]", 1, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("Gen1.der(delta)", "der(Rotor angle) [rad/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("Gen1.Vt", "Bus voltage magnitude [1]", "Eterm", 1, 3, 0, 0)
DeclareVariable("Gen1.anglev", "Bus voltage angle [rad|deg]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.I", "Terminal current magnitude [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.anglei", "Terminal current angle [rad|deg]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("Gen1.P", "Active power (system base) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.Q", "Reactive power (system base) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.Te", "Electrical torque [pu] [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.id", "d-axis armature current [pu] [1]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Gen1.iq", "q-axis armature current [pu] [1]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Gen1.ud", "d-axis terminal voltage [pu] [1]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Gen1.uq", "q-axis terminal voltage [pu] [1]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Gen1.w_b", "System base speed [rad/s]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.CoB", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.vr0", "Real component of initial terminal voltage [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.vi0", "Imaginary component of initial terminal voltage [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.ir0", "Real component of initial armature current (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.ii0", "Imaginary component of initial armature current (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.p0", "Initial active power generation (machine base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.q0", "Initial reactive power generation (machine base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareState("Gen1.Epq", "q-axis voltage behind transient reactance [1]", 2, 0.0,\
 0.0,0.0,0.0,0,544)
DeclareDerivative("Gen1.der(Epq)", "der(q-axis voltage behind transient reactance) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("Gen1.PSIkd", "d-axis rotor flux linkage [1]", 3, 0.0, 0.0,0.0,0.0,\
0,544)
DeclareDerivative("Gen1.der(PSIkd)", "der(d-axis rotor flux linkage) [s-1]", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareState("Gen1.PSIppq", "q-axis subtransient flux linkage [1]", 4, 0.0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("Gen1.der(PSIppq)", "der(q-axis subtransient flux linkage) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.PSIppd", "d-axis subtransient flux linkage [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.PSId", "d-axis flux linkage [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Gen1.PSIq", "q-axis flux linkage [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("Gen1.XadIfd", "Machine field current [1]", "XadIfd", 1, 3, 1, 0)
DeclareVariable("Gen1.Zs.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.Zs.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.Is.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.Is.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.PSIpp0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.PSIpp0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.a.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.a.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.Epqp.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("Gen1.Epqp.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.delta0", "rotor angle in radians [rad]", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("Gen1.VT.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.VT.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.S.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.S.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.It.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.It.im", "Imaginary part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("Gen1.DQ_dq.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("Gen1.DQ_dq.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.I_dq.re", "Real part of complex number", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("Gen1.I_dq.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.iq0", "q-axis component of initial current [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.id0", "d-axis component of initial current [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.ud0", "d-axis component of initial voltage [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.uq0", "q-axis component of initial voltage [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIpp0_dq.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIpp0_dq.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIppq0", "q-axis component of the sub-transient flux linkage [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIppd0", "d-axis component of the sub-transient flux linkage [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIkd0", "d-axis initial rotor flux linkage [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSId0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.PSIq0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.Epq0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.dsat", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.efd0", "Initial field voltage magnitude [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.pm0", "Initial mechanical power (machine base) [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.K1d", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.K2d", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.K3d", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Gen1.K4d", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_b", "System base power [VA|MVA]", 0.0, 0.0,0.0,\
100000000.0,0,513)
DeclareVariable("constantLoad.enableS_b", "Enable S_b in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("constantLoad.V_b", "Base voltage of the bus [V|kV]", 71, \
400000.0, 0.0,0.0,10000.0,0,560)
DeclareVariable("constantLoad.enableV_b", "Enable V_b in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("constantLoad.fn", "System frequency [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("constantLoad.enablefn", "Enable fn in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("constantLoad.P_0", "Initial active power [W|MW]", 72, 0, \
0.0,0.0,100000000.0,0,560)
DeclareVariable("constantLoad.enableP_0", "Enable P_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("constantLoad.Q_0", "Initial reactive power [var|MVA]", 73, 0, \
0.0,0.0,100000000.0,0,560)
DeclareVariable("constantLoad.enableQ_0", "Enable Q_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("constantLoad.v_0", "Initial voltage magnitude [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("constantLoad.enablev_0", "Enable v_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("constantLoad.angle_0", "Initial voltage angle [rad|deg]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("constantLoad.enableangle_0", "Enable angle_0 in parameter list [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareParameter("constantLoad.displayPF", "Display power flow: [:#(type=Boolean)]",\
 74, false, 0.0,0.0,0.0,0,562)
DeclareVariable("constantLoad.enabledisplayPF", "Enable displayPF in parameter list [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("constantLoad.S_p.re", "Real part of complex power (active power) [W|MW]",\
 0.0, 0.0,0.0,100000000.0,0,513)
DeclareVariable("constantLoad.S_p.im", "Imaginary part of complex power (reactive power) [var|MVA]",\
 0.0, 0.0,0.0,100000000.0,0,513)
DeclareParameter("constantLoad.S_i.re", "Real part of complex power (active power) [W|MW]",\
 75, 0.0, 0.0,0.0,100000000.0,0,560)
DeclareParameter("constantLoad.S_i.im", "Imaginary part of complex power (reactive power) [var|MVA]",\
 76, 0.0, 0.0,0.0,100000000.0,0,560)
DeclareParameter("constantLoad.S_y.re", "Real part of complex power (active power) [W|MW]",\
 77, 0.0, 0.0,0.0,100000000.0,0,560)
DeclareParameter("constantLoad.S_y.im", "Imaginary part of complex power (reactive power) [var|MVA]",\
 78, 0.0, 0.0,0.0,100000000.0,0,560)
DeclareParameter("constantLoad.a.re", "Real part of complex number", 79, 1.0, \
0.0,0.0,0.0,0,560)
DeclareParameter("constantLoad.a.im", "Imaginary part of complex number", 80, \
0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("constantLoad.b.re", "Real part of complex number", 81, 0.0, \
0.0,0.0,0.0,0,560)
DeclareParameter("constantLoad.b.im", "Imaginary part of complex number", 82, \
1.0, 0.0,0.0,0.0,0,560)
DeclareVariable("constantLoad.PQBRAK", "Constant power characteristic threshold [1]",\
 0.7, 0.0,0.0,0.0,0,513)
DeclareVariable("constantLoad.characteristic", "[:#(type=Integer)]", 1, 0.0,0.0,\
0.0,0,517)
DeclareAlias2("constantLoad.p.vr", "Real part of the voltage [1]", "bus.p.vr", 1,\
 5, 12, 4)
DeclareAlias2("constantLoad.p.vi", "Imaginary part of the voltage [1]", \
"bus.p.vi", 1, 5, 13, 4)
DeclareVariable("constantLoad.p.ir", "Real part of the current [1]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareVariable("constantLoad.p.ii", "Imaginary part of the current [1]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareVariable("constantLoad.angle", "Bus voltage angle [rad|deg]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("constantLoad.v", "Bus voltage magnitude [1]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("constantLoad.P", "Active power consumption [1]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("constantLoad.Q", "Reactive power consumption [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("constantLoad.p0", "Initial active power [1]", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("constantLoad.q0", "Initial reactive power [1]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("constantLoad.vr0", "Initial real voltage [1]", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("constantLoad.vi0", "Initial imaginary voltage [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.ir0", "Initial real current [1]", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("constantLoad.ii0", "Initial imaginary current [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_P.re", "Real part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_P.im", "Imaginary part of complex number [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_I.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_I.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_Y.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.S_Y.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareParameter("constantLoad.a2", "", 83, 1.502, 0.0,0.0,0.0,0,2608)
DeclareParameter("constantLoad.b2", "", 84, 1.769, 0.0,0.0,0.0,0,2608)
DeclareParameter("constantLoad.a0", "", 85, 0.4881, 0.0,0.0,0.0,0,2608)
DeclareParameter("constantLoad.a1", "", 86, -0.4999, 0.0,0.0,0.0,0,2608)
DeclareParameter("constantLoad.b1", "", 87, 0.1389, 0.0,0.0,0.0,0,2608)
DeclareParameter("constantLoad.wp", "", 88, 3.964, 0.0,0.0,0.0,0,2608)
DeclareVariable("constantLoad.kP", "", 1, 0.0,0.0,0.0,0,2560)
DeclareVariable("constantLoad.kI", "", 1, 0.0,0.0,0.0,0,2561)
DeclareParameter("constantLoad.d_P", "Active Load Variation [1]", 89, 0, \
0.0,0.0,0.0,0,560)
DeclareVariable("constantLoad.t1", "Time of Load Variation [s]", 0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("constantLoad.d_t", "Time duration of load variation [s]", 0, \
0.0,0.0,0.0,0,513)
DeclareVariable("constantLoad.PF", "Ration between active and reactive power; Not Power Factor [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("constantLoad.d_Q", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("constantLoad.u", "[1]", "P", 1, 2, 1, 0)
DeclareAlias2("constantLoad.x", "[1]", "Q", 1, 2, 2, 0)
DeclareInput("EFD1", "Generator main field voltage [pu] [1:#(prefix=input)]", 0,\
 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("Eterm", "Initial generator main field voltage [pu] [1]", 0, 0.0, \
0.0,0.0,0.0,0,512)
DeclareInput("P", "[1:#(prefix=input)]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("Q", "[1:#(prefix=input)]", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("XadIfd", "Machine field current [pu] [1]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("w", "Machine speed deviation from nominal [pu] [rad]", 2, 0.0, \
0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
if (initialCall) DYNX(did_->xInitial_var, 2)=DYNX(X_,3);
else if (DYNHReject) DYNX(X_,3)=did_->xInitial_var2[2]; else did_->xInitial_var2[2]=
  DYNX(X_,3);
if (initialCall) DYNX(did_->xInitial_var, 1)=DYNX(W_,56);
else if (DYNHReject) DYNX(W_,56)=did_->xInitial_var2[1]; else did_->xInitial_var2[1]=
  DYNX(W_,56);
if (initialCall) DYNX(did_->xInitial_var, 0)=DYNX(W_,57);
else if (DYNHReject) DYNX(W_,57)=did_->xInitial_var2[0]; else did_->xInitial_var2[0]=
  DYNX(W_,57);
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,56), DYNX(W_,93), 0);
DoRemember_(DYNX(W_,57), DYNX(W_,92), 1);
EndEqBlock
EndDataBlock
