#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Mostar.Models.AVR_IGLim_Capacitive.FMU.fmu_AVR
 Dymola Version 2019 FD01 (64-bit), 2018-10-10 translated this at Tue Apr 13 12:48:42 2021

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

  BreakSectionDef(1);
BreakSectionFunctionDef(2)
BreakSectionFunctionDef(0)
  BreakSectionDef(3);
  BreakSectionDef(4);
  BreakSectionDef(5);
  BreakSectionDef(6);
  BreakSectionDef(7);
#define NX_    8
#define NX2_   0
#define NU_    2
#define NY_    1
#define NW_    193
#define NP_    105
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   6
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1801675443
#define NHash2_ -17139250
#define NHash3_ 0
#define NI_    0
#define NRelF_ 16
#define NRel_  20
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    101
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 6
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 1
#define NCheckIf_ 0
#define NGlobalHelp_ 234
#define NGlobalHelpI_ 139
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#define DYNCALLFMUREINIT
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Mostar.Models.AVR_IGLim_Capacitive.FMU.fmu_AVR";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/meagh/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
DYMOLA_STATIC const char*GUIDString="{9169b0fb-48c0-4536-b03a-91089b56c2ab}";
DYMOLA_STATIC const double cvodeTolerance=1E-05;
#define FMIStateValueReferencesDef_ 1
DYMOLA_STATIC unsigned int FMIStateValueReferences_[8]={
33554432, 33554433, 33554434, 33554435, 33554436, 33554437, 33554438, 33554439};
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[15]={4 , 3 , 1 , 3 , 5 , 3 , 2 , 4 , 6 , 1 , 7 , 1
   , 8 , 0 , 0};
DYMOLA_STATIC int QJacobianGC_[33]={
1 , 1 , 3 , 3 , 5 , 5 , 1 , 0 , 0 , 2 , 0 , 4 , 0 , 6 , 2 , 0 , 0 , 0 , 0 , 0 , 0
   , 0 , 7 , 0 , 8 , 8 , 8 , 8 , 8 , 8 , 8 , 8 , 0};
DYMOLA_STATIC double QJacobianCD_[9]={0  , 44 , 50 , 66 , 70 , 88 , 90 , 90 , 88};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,39) = false;
DYNX(W_,40) = false;
DYNX(W_,63) = false;
DYNX(W_,64) = false;
DYNX(W_,98) = false;
DYNX(W_,99) = false;
DYNX(W_,122) = false;
DYNX(W_,123) = false;
DYNX(W_,146) = false;
DYNX(W_,147) = false;
DYNX(W_,170) = false;
DYNX(W_,171) = false;
DYNX(W_,41) = 2;
DYNX(W_,48) = false;
DYNX(W_,49) = 2;
DYNX(W_,50) = true;
DYNX(W_,65) = 2;
DYNX(W_,72) = false;
DYNX(W_,73) = 2;
DYNX(W_,74) = true;
DYNX(W_,79) = false;
DYNX(W_,80) = 2;
DYNX(W_,81) = true;
DYNX(W_,100) = 2;
DYNX(W_,107) = false;
DYNX(W_,108) = 2;
DYNX(W_,109) = true;
DYNX(W_,124) = 2;
DYNX(W_,131) = false;
DYNX(W_,132) = 2;
DYNX(W_,133) = true;
DYNX(W_,148) = 2;
DYNX(W_,155) = false;
DYNX(W_,156) = 2;
DYNX(W_,157) = true;
DYNX(W_,172) = 2;
DYNX(W_,179) = false;
DYNX(W_,180) = 2;
DYNX(W_,181) = true;
DYNX(W_,44) = 0;
DYNX(W_,68) = 0;
DYNX(W_,103) = 0;
DYNX(W_,127) = 0;
DYNX(W_,151) = 0;
DYNX(W_,175) = 0;
DYNX(W_,43) = false;
DYNX(W_,102) = false;
DYNX(W_,67) = false;
DYNX(W_,126) = false;
DYNX(W_,150) = false;
DYNX(W_,174) = false;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,6) = DYNX(DP_,20);
DYNX(W_,7) = DYNX(DP_,21);
DYNX(W_,8) = DYNX(DP_,22);
DYNX(W_,9) = DYNX(DP_,23);
DYNX(W_,10) = DYNX(DP_,24);
DYNX(W_,11) = DYNX(DP_,25);
DYNX(W_,12) = DYNX(DP_,26);
DYNX(W_,13) = DYNX(DP_,27);
DYNX(W_,14) = DYNX(DP_,28);
DYNX(W_,15) = DYNX(DP_,29);
DYNX(W_,16) = DYNX(DP_,30);
DYNX(W_,17) = DYNX(DP_,31);
DYNX(W_,18) = DYNX(DP_,32);
DYNX(W_,19) = DYNX(DP_,33);
DYNX(W_,20) = DYNX(DP_,34);
DYNX(W_,21) = DYNX(DP_,35);
DYNX(W_,22) = DYNX(DP_,36);
DYNX(W_,23) = DYNX(DP_,37);
DYNX(W_,28) = DYNX(W_,7);
DYNX(W_,29) = DYNX(W_,8);
DYNX(W_,30) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,31) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,35) = divmacro(DYNX(W_,28),"sT5B.imLimitedLeadLag.T1",DYNX(W_,29),
  "sT5B.imLimitedLeadLag.T2");
DYNX(W_,38) = divmacro(1,"1",DYNX(W_,28),"sT5B.imLimitedLeadLag.T1");
DYNX(W_,45) = divmacro(DYNX(W_,29),"sT5B.imLimitedLeadLag.T2",DYNX(W_,28),
  "sT5B.imLimitedLeadLag.T1")-1;
DYNX(W_,46) = DYNX(W_,30);
DYNX(W_,47) = DYNX(W_,31);
DYNX(W_,52) = DYNX(W_,9);
DYNX(W_,53) = DYNX(W_,10);
DYNX(W_,54) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,55) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,59) = divmacro(DYNX(W_,52),"sT5B.imLimitedLeadLag2.T1",DYNX(W_,53),
  "sT5B.imLimitedLeadLag2.T2");
DYNX(W_,62) = divmacro(1,"1",DYNX(W_,52),"sT5B.imLimitedLeadLag2.T1");
DYNX(W_,69) = divmacro(DYNX(W_,53),"sT5B.imLimitedLeadLag2.T2",DYNX(W_,52),
  "sT5B.imLimitedLeadLag2.T1")-1;
DYNX(W_,70) = DYNX(W_,54);
DYNX(W_,71) = DYNX(W_,55);
DYNX(W_,75) = DYNX(W_,11);
DYNX(W_,77) = DYNX(W_,12);
DYNX(W_,78) = DYNX(W_,13);
DYNX(W_,85) = DYNX(W_,15);
DYNX(W_,87) = DYNX(W_,16);
DYNX(W_,88) = DYNX(W_,17);
DYNX(W_,89) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,90) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,94) = divmacro(DYNX(W_,87),"sT5B.imLimitedLeadLag1.T1",DYNX(W_,88),
  "sT5B.imLimitedLeadLag1.T2");
DYNX(W_,97) = divmacro(1,"1",DYNX(W_,87),"sT5B.imLimitedLeadLag1.T1");
DYNX(W_,104) = divmacro(DYNX(W_,88),"sT5B.imLimitedLeadLag1.T2",DYNX(W_,87),
  "sT5B.imLimitedLeadLag1.T1")-1;
DYNX(W_,105) = DYNX(W_,89);
DYNX(W_,106) = DYNX(W_,90);
DYNX(W_,111) = DYNX(W_,16);
DYNX(W_,112) = DYNX(W_,17);
DYNX(W_,113) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,114) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,118) = divmacro(DYNX(W_,111),"sT5B.imLimitedLeadLag3.T1",DYNX(W_,112),
  "sT5B.imLimitedLeadLag3.T2");
DYNX(W_,121) = divmacro(1,"1",DYNX(W_,111),"sT5B.imLimitedLeadLag3.T1");
DYNX(W_,128) = divmacro(DYNX(W_,112),"sT5B.imLimitedLeadLag3.T2",DYNX(W_,111),
  "sT5B.imLimitedLeadLag3.T1")-1;
DYNX(W_,129) = DYNX(W_,113);
DYNX(W_,130) = DYNX(W_,114);
DYNX(W_,135) = DYNX(W_,20);
DYNX(W_,136) = DYNX(W_,21);
DYNX(W_,137) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,138) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,142) = divmacro(DYNX(W_,135),"sT5B.imLimitedLeadLag4.T1",DYNX(W_,136),
  "sT5B.imLimitedLeadLag4.T2");
DYNX(W_,145) = divmacro(1,"1",DYNX(W_,135),"sT5B.imLimitedLeadLag4.T1");
DYNX(W_,152) = divmacro(DYNX(W_,136),"sT5B.imLimitedLeadLag4.T2",DYNX(W_,135),
  "sT5B.imLimitedLeadLag4.T1")-1;
DYNX(W_,153) = DYNX(W_,137);
DYNX(W_,154) = DYNX(W_,138);
DYNX(W_,159) = DYNX(W_,20);
DYNX(W_,160) = DYNX(W_,21);
DYNX(W_,161) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,162) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,166) = divmacro(DYNX(W_,159),"sT5B.imLimitedLeadLag5.T1",DYNX(W_,160),
  "sT5B.imLimitedLeadLag5.T2");
DYNX(W_,169) = divmacro(1,"1",DYNX(W_,159),"sT5B.imLimitedLeadLag5.T1");
DYNX(W_,176) = divmacro(DYNX(W_,160),"sT5B.imLimitedLeadLag5.T2",DYNX(W_,159),
  "sT5B.imLimitedLeadLag5.T1")-1;
DYNX(W_,177) = DYNX(W_,161);
DYNX(W_,178) = DYNX(W_,162);
DYNX(W_,184) = DYNX(W_,14);
DYNX(W_,186) = IF DYNX(W_,184) < 1E-15 THEN 1000 ELSE DYNX(W_,184);
DYNX(W_,187) = DYNX(W_,12);
DYNX(W_,188) = DYNX(W_,13);
DYNX(W_,189) = DYNX(W_,6);
DYNX(W_,191) = IF DYNX(W_,189) < 1E-15 THEN 1000 ELSE DYNX(W_,189);
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,1) = DYNX(W_,190);
DYNX(X_,0) = DYNX(W_,42);
DYNX(X_,1) = DYNX(W_,66);
DYNX(X_,2) = DYNX(W_,101);
DYNX(X_,3) = DYNX(W_,125);
DYNX(X_,4) = DYNX(W_,149);
DYNX(X_,5) = DYNX(W_,173);
DYNX(X_,7) = DYNX(W_,190);
DYNX(Y_,0) = DYNX(W_,185);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,0) = 0;
DYNX(F_,1) = 0;
DYNX(F_,2) = 0;
DYNX(F_,3) = 0;
DYNX(F_,4) = 0;
DYNX(F_,5) = 0;
DYNX(W_,15) = DYNX(DP_,29);
DYNX(W_,11) = DYNX(DP_,25);
DYNX(W_,3) = DYNX(DP_,104);
DYNX(W_,192) = DYNX(W_,3)+DYNX(W_,15)*DYNX(U_,1);
DYNX(W_,4) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R")+DYNX(U_,0);
DYNX(W_,0) = DYNX(W_,4);
DYNX(W_,6) = DYNX(DP_,20);
DYNX(W_,7) = DYNX(DP_,21);
DYNX(W_,8) = DYNX(DP_,22);
DYNX(W_,9) = DYNX(DP_,23);
DYNX(W_,10) = DYNX(DP_,24);
DYNX(W_,12) = DYNX(DP_,26);
DYNX(W_,13) = DYNX(DP_,27);
DYNX(W_,14) = DYNX(DP_,28);
DYNX(W_,16) = DYNX(DP_,30);
DYNX(W_,17) = DYNX(DP_,31);
DYNX(W_,18) = DYNX(DP_,32);
DYNX(W_,19) = DYNX(DP_,33);
DYNX(W_,20) = DYNX(DP_,34);
DYNX(W_,21) = DYNX(DP_,35);
DYNX(W_,22) = DYNX(DP_,36);
DYNX(W_,23) = DYNX(DP_,37);
DYNX(W_,28) = DYNX(W_,7);
DYNX(W_,29) = DYNX(W_,8);
DYNX(W_,30) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,31) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,32) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,35) = divmacro(DYNX(W_,28),"sT5B.imLimitedLeadLag.T1",DYNX(W_,29),
  "sT5B.imLimitedLeadLag.T2");
DYNX(W_,38) = divmacro(1,"1",DYNX(W_,28),"sT5B.imLimitedLeadLag.T1");
DYNX(W_,42) = DYNX(W_,32);
DYNX(W_,45) = divmacro(DYNX(W_,29),"sT5B.imLimitedLeadLag.T2",DYNX(W_,28),
  "sT5B.imLimitedLeadLag.T1")-1;
DYNX(W_,46) = DYNX(W_,30);
DYNX(W_,47) = DYNX(W_,31);
AssertModelica(DYNX(W_,46) >= DYNX(W_,47),"sT5B.imLimitedLeadLag.limiter.uMax >= sT5B.imLimitedLeadLag.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,46), true, 0)),") < uMin (="),Real2String2(DYNX(W_,47), 
  true, 0)),")"));
PopAllMarks();
DYNX(W_,52) = DYNX(W_,9);
DYNX(W_,53) = DYNX(W_,10);
DYNX(W_,54) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,55) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,56) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,59) = divmacro(DYNX(W_,52),"sT5B.imLimitedLeadLag2.T1",DYNX(W_,53),
  "sT5B.imLimitedLeadLag2.T2");
DYNX(W_,62) = divmacro(1,"1",DYNX(W_,52),"sT5B.imLimitedLeadLag2.T1");
DYNX(W_,66) = DYNX(W_,56);
DYNX(W_,69) = divmacro(DYNX(W_,53),"sT5B.imLimitedLeadLag2.T2",DYNX(W_,52),
  "sT5B.imLimitedLeadLag2.T1")-1;
DYNX(W_,70) = DYNX(W_,54);
DYNX(W_,71) = DYNX(W_,55);
AssertModelica(DYNX(W_,70) >= DYNX(W_,71),"sT5B.imLimitedLeadLag2.limiter.uMax >= sT5B.imLimitedLeadLag2.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,70), true, 0)),") < uMin (="),Real2String2(DYNX(W_,71), 
  true, 0)),")"));
PopAllMarks();
DYNX(W_,75) = DYNX(W_,11);
DYNX(W_,77) = DYNX(W_,12);
DYNX(W_,78) = DYNX(W_,13);
AssertModelica(DYNX(W_,77) >= DYNX(W_,78),"sT5B.limiter.uMax >= sT5B.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,77), true, 0)),") < uMin (="),Real2String2(DYNX(W_,78), 
  true, 0)),")"));
PopAllMarks();
DYNX(W_,85) = DYNX(W_,15);
DYNX(W_,87) = DYNX(W_,16);
DYNX(W_,88) = DYNX(W_,17);
DYNX(W_,89) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,90) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,91) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,94) = divmacro(DYNX(W_,87),"sT5B.imLimitedLeadLag1.T1",DYNX(W_,88),
  "sT5B.imLimitedLeadLag1.T2");
DYNX(W_,97) = divmacro(1,"1",DYNX(W_,87),"sT5B.imLimitedLeadLag1.T1");
DYNX(W_,101) = DYNX(W_,91);
DYNX(W_,104) = divmacro(DYNX(W_,88),"sT5B.imLimitedLeadLag1.T2",DYNX(W_,87),
  "sT5B.imLimitedLeadLag1.T1")-1;
DYNX(W_,105) = DYNX(W_,89);
DYNX(W_,106) = DYNX(W_,90);
AssertModelica(DYNX(W_,105) >= DYNX(W_,106),"sT5B.imLimitedLeadLag1.limiter.uMax >= sT5B.imLimitedLeadLag1.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,105), true, 0)),") < uMin (="),Real2String2(DYNX(W_,106),
   true, 0)),")"));
PopAllMarks();
DYNX(W_,111) = DYNX(W_,16);
DYNX(W_,112) = DYNX(W_,17);
DYNX(W_,113) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,114) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,115) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,118) = divmacro(DYNX(W_,111),"sT5B.imLimitedLeadLag3.T1",DYNX(W_,112),
  "sT5B.imLimitedLeadLag3.T2");
DYNX(W_,121) = divmacro(1,"1",DYNX(W_,111),"sT5B.imLimitedLeadLag3.T1");
DYNX(W_,125) = DYNX(W_,115);
DYNX(W_,128) = divmacro(DYNX(W_,112),"sT5B.imLimitedLeadLag3.T2",DYNX(W_,111),
  "sT5B.imLimitedLeadLag3.T1")-1;
DYNX(W_,129) = DYNX(W_,113);
DYNX(W_,130) = DYNX(W_,114);
AssertModelica(DYNX(W_,129) >= DYNX(W_,130),"sT5B.imLimitedLeadLag3.limiter.uMax >= sT5B.imLimitedLeadLag3.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,129), true, 0)),") < uMin (="),Real2String2(DYNX(W_,130),
   true, 0)),")"));
PopAllMarks();
DYNX(W_,135) = DYNX(W_,20);
DYNX(W_,136) = DYNX(W_,21);
DYNX(W_,137) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,138) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,139) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,142) = divmacro(DYNX(W_,135),"sT5B.imLimitedLeadLag4.T1",DYNX(W_,136),
  "sT5B.imLimitedLeadLag4.T2");
DYNX(W_,145) = divmacro(1,"1",DYNX(W_,135),"sT5B.imLimitedLeadLag4.T1");
DYNX(W_,149) = DYNX(W_,139);
DYNX(W_,152) = divmacro(DYNX(W_,136),"sT5B.imLimitedLeadLag4.T2",DYNX(W_,135),
  "sT5B.imLimitedLeadLag4.T1")-1;
DYNX(W_,153) = DYNX(W_,137);
DYNX(W_,154) = DYNX(W_,138);
AssertModelica(DYNX(W_,153) >= DYNX(W_,154),"sT5B.imLimitedLeadLag4.limiter.uMax >= sT5B.imLimitedLeadLag4.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,153), true, 0)),") < uMin (="),Real2String2(DYNX(W_,154),
   true, 0)),")"));
PopAllMarks();
DYNX(W_,159) = DYNX(W_,20);
DYNX(W_,160) = DYNX(W_,21);
DYNX(W_,161) = divmacro(DYNX(W_,12),"sT5B.V_RMAX",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,162) = divmacro(DYNX(W_,13),"sT5B.V_RMIN",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,163) = divmacro(DYNX(W_,192),"sT5B.VR0",DYNX(W_,11),"sT5B.K_R");
DYNX(W_,166) = divmacro(DYNX(W_,159),"sT5B.imLimitedLeadLag5.T1",DYNX(W_,160),
  "sT5B.imLimitedLeadLag5.T2");
DYNX(W_,169) = divmacro(1,"1",DYNX(W_,159),"sT5B.imLimitedLeadLag5.T1");
DYNX(W_,173) = DYNX(W_,163);
DYNX(W_,176) = divmacro(DYNX(W_,160),"sT5B.imLimitedLeadLag5.T2",DYNX(W_,159),
  "sT5B.imLimitedLeadLag5.T1")-1;
DYNX(W_,177) = DYNX(W_,161);
DYNX(W_,178) = DYNX(W_,162);
AssertModelica(DYNX(W_,177) >= DYNX(W_,178),"sT5B.imLimitedLeadLag5.limiter.uMax >= sT5B.imLimitedLeadLag5.limiter.uMin",
   StringAdd(StringAdd(StringAdd(StringAdd("Limiter: Limits must be consistent. However, uMax (=",
  Real2String2(DYNX(W_,177), true, 0)),") < uMin (="),Real2String2(DYNX(W_,178),
   true, 0)),")"));
PopAllMarks();
DYNX(W_,184) = DYNX(W_,14);
DYNX(W_,185) = DYNX(W_,3);
DYNX(W_,186) = IF DYNX(W_,184) < 1E-15 THEN 1000 ELSE DYNX(W_,184);
DYNX(W_,187) = DYNX(W_,12);
DYNX(W_,188) = DYNX(W_,13);
DYNX(W_,189) = DYNX(W_,6);
DYNX(W_,5) = DYNX(U_,0);
DYNX(W_,190) = DYNX(W_,5);
DYNX(W_,191) = IF DYNX(W_,189) < 1E-15 THEN 1000 ELSE DYNX(W_,189);
DYNX(X_,7) = DYNX(W_,190);
 /* Linear system of equations to solve. */
DYNX(W_,37) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,38)," -sT5B.imLimitedLeadLag.integrator.k",
   0.0,"0.0", DYNX(W_,37),"sT5B.imLimitedLeadLag.add3.y");
 /* End of Equation Block */ 

DYNX(W_,1) = IF fabs(DYNX(W_,189)) <= 1E-15 THEN DYNX(U_,0)*DYNX(DP_,102) ELSE 
  DYNX(X_,7);
DYNX(W_,2) = DYNX(DP_,65)*DYNX(W_,0)+DYNX(DP_,66)*DYNX(W_,1);
DYNX(W_,26) = IF Less(DYNX(DP_,63),"const1.k", DYNX(W_,2),"sT5B.DiffV.y", 0)
   THEN DYNX(W_,2) ELSE DYNX(DP_,63);
DYNX(W_,24) = IF Greater(DYNX(DP_,64),"const2.k", DYNX(W_,26),"sT5B.lV_Gate.n2",
   1) THEN DYNX(W_,26) ELSE DYNX(DP_,64);
DYNX(W_,25) = DYNX(DP_,67)*DYNX(DP_,103)+DYNX(DP_,68)*DYNX(W_,24);
if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(1);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[1] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 1, -2, 
    DYNX(DYNhelp,2), 35, DYNX(did_->helpvari_vec,0), 23);
  SetInitVector(x__, 1, DYNX(X_,0), DYNX(W_,42));
  Residues;
    DYNX(W_,33) = DYNX(W_,45)*DYNX(X_,0);
    DYNX(W_,34) = DYNX(DP_,70)*DYNX(W_,25)+DYNX(DP_,71)*DYNX(W_,33);
    DYNX(W_,36) = DYNX(W_,35)*DYNX(W_,34);
    DYNX(DYNhelp,37) = GreaterS(DYNX(W_,36),"sT5B.imLimitedLeadLag.gain.y", 
      DYNX(W_,46),"sT5B.imLimitedLeadLag.limiter.uMax", 2);
    DYNX(W_,27) = homotopy(IF DYNX(DYNhelp,37) THEN DYNX(W_,46) ELSE IF LessS(
      DYNX(W_,36),"sT5B.imLimitedLeadLag.gain.y", DYNX(W_,47),"sT5B.imLimitedLeadLag.limiter.uMin",
       3) THEN DYNX(W_,47) ELSE DYNX(W_,36), DYNX(W_,36));
  SetVector(residue__, 1, DYNX(W_,37)-(DYNX(DP_,72)*DYNX(W_,27)+DYNX(DP_,73)*
    DYNX(X_,0)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,73)+DYNX(DP_,71)*DYNX(W_,35)
    *homotopy(IF DYNX(DYNhelp,37) THEN 0.0 ELSE IF LessS(DYNX(W_,36),
    "sT5B.imLimitedLeadLag.gain.y", DYNX(W_,47),"sT5B.imLimitedLeadLag.limiter.uMin",
     3) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,72)*DYNX(W_,45)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[1]");
  DYNX(X_,0) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 1);
   /* End of Non-Linear Equation Block */ }



}
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(2);
 /* Linear system of equations to solve. */
DYNX(W_,61) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,62)," -sT5B.imLimitedLeadLag2.integrator.k",
   0.0,"0.0", DYNX(W_,61),"sT5B.imLimitedLeadLag2.add3.y");
 /* End of Equation Block */ 

if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(3);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[2] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag2.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 2, -2, 
    DYNX(DYNhelp,40), 35, DYNX(did_->helpvari_vec,23), 23);
  SetInitVector(x__, 1, DYNX(X_,1), DYNX(W_,66));
  Residues;
    DYNX(W_,57) = DYNX(W_,69)*DYNX(X_,1);
    DYNX(W_,58) = DYNX(DP_,75)*DYNX(W_,27)+DYNX(DP_,76)*DYNX(W_,57);
    DYNX(W_,60) = DYNX(W_,59)*DYNX(W_,58);
    DYNX(DYNhelp,75) = GreaterS(DYNX(W_,60),"sT5B.imLimitedLeadLag2.gain.y", 
      DYNX(W_,70),"sT5B.imLimitedLeadLag2.limiter.uMax", 4);
    DYNX(W_,51) = homotopy(IF DYNX(DYNhelp,75) THEN DYNX(W_,70) ELSE IF LessS(
      DYNX(W_,60),"sT5B.imLimitedLeadLag2.gain.y", DYNX(W_,71),"sT5B.imLimitedLeadLag2.limiter.uMin",
       5) THEN DYNX(W_,71) ELSE DYNX(W_,60), DYNX(W_,60));
  SetVector(residue__, 1, DYNX(W_,61)-(DYNX(DP_,77)*DYNX(W_,51)+DYNX(DP_,78)*
    DYNX(X_,1)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,78)+DYNX(DP_,76)*DYNX(W_,59)
    *homotopy(IF DYNX(DYNhelp,75) THEN 0.0 ELSE IF LessS(DYNX(W_,60),
    "sT5B.imLimitedLeadLag2.gain.y", DYNX(W_,71),"sT5B.imLimitedLeadLag2.limiter.uMin",
     5) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,77)*DYNX(W_,69)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[2]");
  DYNX(X_,1) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 2);
   /* End of Non-Linear Equation Block */ }



}
 /* Linear system of equations to solve. */
DYNX(W_,96) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,97)," -sT5B.imLimitedLeadLag1.integrator.k",
   0.0,"0.0", DYNX(W_,96),"sT5B.imLimitedLeadLag1.add3.y");
 /* End of Equation Block */ 

if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(4);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[3] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag1.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 3, -2, 
    DYNX(DYNhelp,78), 35, DYNX(did_->helpvari_vec,46), 23);
  SetInitVector(x__, 1, DYNX(X_,2), DYNX(W_,101));
  Residues;
    DYNX(W_,92) = DYNX(W_,104)*DYNX(X_,2);
    DYNX(W_,93) = DYNX(DP_,82)*DYNX(W_,25)+DYNX(DP_,83)*DYNX(W_,92);
    DYNX(W_,95) = DYNX(W_,94)*DYNX(W_,93);
    DYNX(DYNhelp,113) = GreaterS(DYNX(W_,95),"sT5B.imLimitedLeadLag1.gain.y", 
      DYNX(W_,105),"sT5B.imLimitedLeadLag1.limiter.uMax", 6);
    DYNX(W_,86) = homotopy(IF DYNX(DYNhelp,113) THEN DYNX(W_,105) ELSE IF LessS(
      DYNX(W_,95),"sT5B.imLimitedLeadLag1.gain.y", DYNX(W_,106),"sT5B.imLimitedLeadLag1.limiter.uMin",
       7) THEN DYNX(W_,106) ELSE DYNX(W_,95), DYNX(W_,95));
  SetVector(residue__, 1, DYNX(W_,96)-(DYNX(DP_,84)*DYNX(W_,86)+DYNX(DP_,85)*
    DYNX(X_,2)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,85)+DYNX(DP_,83)*DYNX(W_,94)
    *homotopy(IF DYNX(DYNhelp,113) THEN 0.0 ELSE IF LessS(DYNX(W_,95),
    "sT5B.imLimitedLeadLag1.gain.y", DYNX(W_,106),"sT5B.imLimitedLeadLag1.limiter.uMin",
     7) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,84)*DYNX(W_,104)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[3]");
  DYNX(X_,2) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 3);
   /* End of Non-Linear Equation Block */ }



}
 /* Linear system of equations to solve. */
DYNX(W_,120) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,121)," -sT5B.imLimitedLeadLag3.integrator.k",
   0.0,"0.0", DYNX(W_,120),"sT5B.imLimitedLeadLag3.add3.y");
 /* End of Equation Block */ 

if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(5);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[4] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag3.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 4, -2, 
    DYNX(DYNhelp,116), 35, DYNX(did_->helpvari_vec,69), 23);
  SetInitVector(x__, 1, DYNX(X_,3), DYNX(W_,125));
  Residues;
    DYNX(W_,116) = DYNX(W_,128)*DYNX(X_,3);
    DYNX(W_,117) = DYNX(DP_,87)*DYNX(W_,86)+DYNX(DP_,88)*DYNX(W_,116);
    DYNX(W_,119) = DYNX(W_,118)*DYNX(W_,117);
    DYNX(DYNhelp,151) = GreaterS(DYNX(W_,119),"sT5B.imLimitedLeadLag3.gain.y", 
      DYNX(W_,129),"sT5B.imLimitedLeadLag3.limiter.uMax", 8);
    DYNX(W_,110) = homotopy(IF DYNX(DYNhelp,151) THEN DYNX(W_,129) ELSE IF LessS
      (DYNX(W_,119),"sT5B.imLimitedLeadLag3.gain.y", DYNX(W_,130),
      "sT5B.imLimitedLeadLag3.limiter.uMin", 9) THEN DYNX(W_,130) ELSE 
      DYNX(W_,119), DYNX(W_,119));
  SetVector(residue__, 1, DYNX(W_,120)-(DYNX(DP_,89)*DYNX(W_,110)+DYNX(DP_,90)*
    DYNX(X_,3)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,90)+DYNX(DP_,88)*
    DYNX(W_,118)*homotopy(IF DYNX(DYNhelp,151) THEN 0.0 ELSE IF LessS(
    DYNX(W_,119),"sT5B.imLimitedLeadLag3.gain.y", DYNX(W_,130),"sT5B.imLimitedLeadLag3.limiter.uMin",
     9) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,89)*DYNX(W_,128)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[4]");
  DYNX(X_,3) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 4);
   /* End of Non-Linear Equation Block */ }



}
 /* Linear system of equations to solve. */
DYNX(W_,144) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,145)," -sT5B.imLimitedLeadLag4.integrator.k",
   0.0,"0.0", DYNX(W_,144),"sT5B.imLimitedLeadLag4.add3.y");
 /* End of Equation Block */ 

if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(6);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[5] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag4.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 5, -2, 
    DYNX(DYNhelp,154), 35, DYNX(did_->helpvari_vec,92), 23);
  SetInitVector(x__, 1, DYNX(X_,4), DYNX(W_,149));
  Residues;
    DYNX(W_,140) = DYNX(W_,152)*DYNX(X_,4);
    DYNX(W_,141) = DYNX(DP_,92)*DYNX(W_,25)+DYNX(DP_,93)*DYNX(W_,140);
    DYNX(W_,143) = DYNX(W_,142)*DYNX(W_,141);
    DYNX(DYNhelp,189) = GreaterS(DYNX(W_,143),"sT5B.imLimitedLeadLag4.gain.y", 
      DYNX(W_,153),"sT5B.imLimitedLeadLag4.limiter.uMax", 10);
    DYNX(W_,134) = homotopy(IF DYNX(DYNhelp,189) THEN DYNX(W_,153) ELSE IF LessS
      (DYNX(W_,143),"sT5B.imLimitedLeadLag4.gain.y", DYNX(W_,154),
      "sT5B.imLimitedLeadLag4.limiter.uMin", 11) THEN DYNX(W_,154) ELSE 
      DYNX(W_,143), DYNX(W_,143));
  SetVector(residue__, 1, DYNX(W_,144)-(DYNX(DP_,94)*DYNX(W_,134)+DYNX(DP_,95)*
    DYNX(X_,4)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,95)+DYNX(DP_,93)*
    DYNX(W_,142)*homotopy(IF DYNX(DYNhelp,189) THEN 0.0 ELSE IF LessS(
    DYNX(W_,143),"sT5B.imLimitedLeadLag4.gain.y", DYNX(W_,154),"sT5B.imLimitedLeadLag4.limiter.uMin",
     11) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,94)*DYNX(W_,152)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[5]");
  DYNX(X_,4) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 5);
   /* End of Non-Linear Equation Block */ }



}
 /* Linear system of equations to solve. */
DYNX(W_,168) = 0.0;
SolveScalarLinearParametric( -DYNX(W_,169)," -sT5B.imLimitedLeadLag5.integrator.k",
   0.0,"0.0", DYNX(W_,168),"sT5B.imLimitedLeadLag5.add3.y");
 /* End of Equation Block */ 

if (DymolaHomotopyLambda==0){
  BreakSectionCallNew(7);
}
else {

  { /* Non-linear system of equations to solve. */
  /* Tag: initialization.nonlinear[6] */
  /* Introducing 1 common subexpressions used in 1 expressions */
  /* Of the common subexpressions 0 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"sT5B.imLimitedLeadLag5.integrator.y"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 0, 6, -2, 
    DYNX(DYNhelp,192), 35, DYNX(did_->helpvari_vec,115), 23);
  SetInitVector(x__, 1, DYNX(X_,5), DYNX(W_,173));
  Residues;
    DYNX(W_,164) = DYNX(W_,176)*DYNX(X_,5);
    DYNX(W_,165) = DYNX(DP_,97)*DYNX(W_,134)+DYNX(DP_,98)*DYNX(W_,164);
    DYNX(W_,167) = DYNX(W_,166)*DYNX(W_,165);
    DYNX(DYNhelp,227) = GreaterS(DYNX(W_,167),"sT5B.imLimitedLeadLag5.gain.y", 
      DYNX(W_,177),"sT5B.imLimitedLeadLag5.limiter.uMax", 12);
    DYNX(W_,158) = homotopy(IF DYNX(DYNhelp,227) THEN DYNX(W_,177) ELSE IF LessS
      (DYNX(W_,167),"sT5B.imLimitedLeadLag5.gain.y", DYNX(W_,178),
      "sT5B.imLimitedLeadLag5.limiter.uMin", 13) THEN DYNX(W_,178) ELSE 
      DYNX(W_,167), DYNX(W_,167));
  SetVector(residue__, 1, DYNX(W_,168)-(DYNX(DP_,99)*DYNX(W_,158)+DYNX(DP_,100)*
    DYNX(X_,5)));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -(DYNX(DP_,100)+DYNX(DP_,98)*
    DYNX(W_,166)*homotopy(IF DYNX(DYNhelp,227) THEN 0.0 ELSE IF LessS(
    DYNX(W_,167),"sT5B.imLimitedLeadLag5.gain.y", DYNX(W_,178),"sT5B.imLimitedLeadLag5.limiter.uMin",
     13) THEN 0.0 ELSE 1.0, 1.0)*DYNX(DP_,99)*DYNX(W_,176)));

  SolveNonLinearSystemOfEquationsInit(Jacobian__, 0, 0, 0, residue__, x__,"Tag: initialization.nonlinear[6]");
  DYNX(X_,5) = GetVector(x__, 1);
  EndNonLinearSystemOfEquationsInit(residue__, x__, 6);
   /* End of Non-Linear Equation Block */ }



}
DYNX(X_,6) = DYNX(W_,185);
DYNX(W_,76) = DYNX(W_,75)*DYNX(W_,51);
DYNX(W_,82) = homotopy(IF GreaterS(DYNX(W_,76),"sT5B.K_r.y", DYNX(W_,77),
  "sT5B.limiter.uMax", 14) THEN DYNX(W_,77) ELSE IF LessS(DYNX(W_,76),
  "sT5B.K_r.y", DYNX(W_,78),"sT5B.limiter.uMin", 15) THEN DYNX(W_,78) ELSE 
  DYNX(W_,76), DYNX(W_,76));
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,33) = DYNX(W_,45)*DYNX(X_,0);
DYNX(W_,57) = DYNX(W_,69)*DYNX(X_,1);
DYNX(W_,83) = DYNX(W_,85)*DYNX(U_,1);
if (NewParameters_) {
DYNX(DYNhelp,228) = fabs(DYNX(W_,189));
}
DYNX(W_,1) = IF DYNX(DYNhelp,228) <= 1E-15 THEN DYNX(U_,0)*DYNX(DP_,102) ELSE 
  DYNX(X_,7);
DYNX(W_,2) = DYNX(DP_,65)*DYNX(W_,0)+DYNX(DP_,66)*DYNX(W_,1);
DYNX(W_,26) = IF Less(DYNX(DP_,63),"const1.k", DYNX(W_,2),"sT5B.DiffV.y", 0)
   THEN DYNX(W_,2) ELSE DYNX(DP_,63);
DYNX(W_,24) = IF Greater(DYNX(DP_,64),"const2.k", DYNX(W_,26),"sT5B.lV_Gate.n2",
   1) THEN DYNX(W_,26) ELSE DYNX(DP_,64);
DYNX(W_,25) = DYNX(DP_,67)*DYNX(DP_,103)+DYNX(DP_,68)*DYNX(W_,24);
DYNX(W_,34) = DYNX(DP_,70)*DYNX(W_,25)+DYNX(DP_,71)*DYNX(W_,33);
DYNX(W_,36) = DYNX(W_,35)*DYNX(W_,34);
DYNX(W_,27) = IF GreaterS(DYNX(W_,36),"sT5B.imLimitedLeadLag.gain.y", 
  DYNX(W_,46),"sT5B.imLimitedLeadLag.limiter.uMax", 2) THEN DYNX(W_,46) ELSE IF 
  LessS(DYNX(W_,36),"sT5B.imLimitedLeadLag.gain.y", DYNX(W_,47),"sT5B.imLimitedLeadLag.limiter.uMin",
   3) THEN DYNX(W_,47) ELSE DYNX(W_,36);
DYNX(W_,58) = DYNX(DP_,75)*DYNX(W_,27)+DYNX(DP_,76)*DYNX(W_,57);
DYNX(W_,60) = DYNX(W_,59)*DYNX(W_,58);
DYNX(W_,51) = IF GreaterS(DYNX(W_,60),"sT5B.imLimitedLeadLag2.gain.y", 
  DYNX(W_,70),"sT5B.imLimitedLeadLag2.limiter.uMax", 4) THEN DYNX(W_,70) ELSE 
  IF LessS(DYNX(W_,60),"sT5B.imLimitedLeadLag2.gain.y", DYNX(W_,71),
  "sT5B.imLimitedLeadLag2.limiter.uMin", 5) THEN DYNX(W_,71) ELSE DYNX(W_,60);
DYNX(W_,76) = DYNX(W_,75)*DYNX(W_,51);
DYNX(W_,82) = IF GreaterS(DYNX(W_,76),"sT5B.K_r.y", DYNX(W_,77),"sT5B.limiter.uMax",
   14) THEN DYNX(W_,77) ELSE IF LessS(DYNX(W_,76),"sT5B.K_r.y", DYNX(W_,78),
  "sT5B.limiter.uMin", 15) THEN DYNX(W_,78) ELSE DYNX(W_,76);
DYNX(W_,84) = DYNX(DP_,79)*DYNX(W_,83)+DYNX(DP_,80)*DYNX(W_,82);
DYNX(W_,182) = DYNX(W_,187)*DYNX(U_,0);
DYNX(W_,183) = DYNX(W_,188)*DYNX(U_,0);
if (NewParameters_) {
DYNX(DYNhelp,229) = fabs(DYNX(W_,184));
}
DYNX(Y_,0) = IF DYNX(DYNhelp,229) <= 1E-15 THEN RealBmax(RealBmin(DYNX(W_,84)*
  DYNX(DP_,101), DYNX(W_,182)), DYNX(W_,183)) ELSE RealBmax(RealBmin(DYNX(X_,6),
   DYNX(W_,182)), DYNX(W_,183));

DynamicsSection
 /* Linear system of equations to solve. */
DYNX(F_,7) = RememberSimple_(DYNX(F_,7), 0);
SolveScalarLinearParametric(DYNX(W_,191),"sT5B.TransducerDelay.T_mod", 
  DYNX(DP_,102)*DYNX(U_,0)-DYNX(X_,7),"sT5B.TransducerDelay.K*V-sT5B.TransducerDelay.state",
   DYNX(F_,7),"der(sT5B.TransducerDelay.state)");
 /* End of Equation Block */ 

DYNX(W_,37) = DYNX(DP_,72)*DYNX(W_,27)+DYNX(DP_,73)*DYNX(X_,0);
DYNX(F_,0) = DYNX(W_,38)*DYNX(W_,37);
DYNX(W_,61) = DYNX(DP_,77)*DYNX(W_,51)+DYNX(DP_,78)*DYNX(X_,1);
DYNX(F_,1) = DYNX(W_,62)*DYNX(W_,61);
DYNX(W_,92) = DYNX(W_,104)*DYNX(X_,2);
DYNX(W_,93) = DYNX(DP_,82)*DYNX(W_,25)+DYNX(DP_,83)*DYNX(W_,92);
DYNX(W_,95) = DYNX(W_,94)*DYNX(W_,93);
DYNX(W_,86) = IF GreaterS(DYNX(W_,95),"sT5B.imLimitedLeadLag1.gain.y", 
  DYNX(W_,105),"sT5B.imLimitedLeadLag1.limiter.uMax", 6) THEN DYNX(W_,105) ELSE 
  IF LessS(DYNX(W_,95),"sT5B.imLimitedLeadLag1.gain.y", DYNX(W_,106),
  "sT5B.imLimitedLeadLag1.limiter.uMin", 7) THEN DYNX(W_,106) ELSE DYNX(W_,95);
DYNX(W_,96) = DYNX(DP_,84)*DYNX(W_,86)+DYNX(DP_,85)*DYNX(X_,2);
DYNX(F_,2) = DYNX(W_,97)*DYNX(W_,96);
DYNX(W_,116) = DYNX(W_,128)*DYNX(X_,3);
DYNX(W_,117) = DYNX(DP_,87)*DYNX(W_,86)+DYNX(DP_,88)*DYNX(W_,116);
DYNX(W_,119) = DYNX(W_,118)*DYNX(W_,117);
DYNX(W_,110) = IF GreaterS(DYNX(W_,119),"sT5B.imLimitedLeadLag3.gain.y", 
  DYNX(W_,129),"sT5B.imLimitedLeadLag3.limiter.uMax", 8) THEN DYNX(W_,129) ELSE 
  IF LessS(DYNX(W_,119),"sT5B.imLimitedLeadLag3.gain.y", DYNX(W_,130),
  "sT5B.imLimitedLeadLag3.limiter.uMin", 9) THEN DYNX(W_,130) ELSE DYNX(W_,119);
DYNX(W_,120) = DYNX(DP_,89)*DYNX(W_,110)+DYNX(DP_,90)*DYNX(X_,3);
DYNX(F_,3) = DYNX(W_,121)*DYNX(W_,120);
DYNX(W_,140) = DYNX(W_,152)*DYNX(X_,4);
DYNX(W_,141) = DYNX(DP_,92)*DYNX(W_,25)+DYNX(DP_,93)*DYNX(W_,140);
DYNX(W_,143) = DYNX(W_,142)*DYNX(W_,141);
DYNX(W_,134) = IF GreaterS(DYNX(W_,143),"sT5B.imLimitedLeadLag4.gain.y", 
  DYNX(W_,153),"sT5B.imLimitedLeadLag4.limiter.uMax", 10) THEN DYNX(W_,153)
   ELSE IF LessS(DYNX(W_,143),"sT5B.imLimitedLeadLag4.gain.y", DYNX(W_,154),
  "sT5B.imLimitedLeadLag4.limiter.uMin", 11) THEN DYNX(W_,154) ELSE DYNX(W_,143);
DYNX(W_,144) = DYNX(DP_,94)*DYNX(W_,134)+DYNX(DP_,95)*DYNX(X_,4);
DYNX(F_,4) = DYNX(W_,145)*DYNX(W_,144);
DYNX(W_,164) = DYNX(W_,176)*DYNX(X_,5);
DYNX(W_,165) = DYNX(DP_,97)*DYNX(W_,134)+DYNX(DP_,98)*DYNX(W_,164);
DYNX(W_,167) = DYNX(W_,166)*DYNX(W_,165);
DYNX(W_,158) = IF GreaterS(DYNX(W_,167),"sT5B.imLimitedLeadLag5.gain.y", 
  DYNX(W_,177),"sT5B.imLimitedLeadLag5.limiter.uMax", 12) THEN DYNX(W_,177)
   ELSE IF LessS(DYNX(W_,167),"sT5B.imLimitedLeadLag5.gain.y", DYNX(W_,178),
  "sT5B.imLimitedLeadLag5.limiter.uMin", 13) THEN DYNX(W_,178) ELSE DYNX(W_,167);
DYNX(W_,168) = DYNX(DP_,99)*DYNX(W_,158)+DYNX(DP_,100)*DYNX(X_,5);
DYNX(F_,5) = DYNX(W_,169)*DYNX(W_,168);
 /* Linear system of equations to solve. */
DYNX(F_,6) = RememberSimple_(DYNX(F_,6), 1);
SolveScalarLinearParametric(DYNX(W_,186),"sT5B.simpleLagLimVar.T_mod", 
  DYNX(W_,84)-DYNX(Y_,0),"sT5B.VERR2.y-Efd", DYNX(F_,6),"der(sT5B.simpleLagLimVar.state)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
CrossingSection
/* Start of reinit equations */
beginwhenBlock
DYNX(DYNhelp,230) = fabs(DYNX(Y_,0)-DYNX(W_,182));
DYNX(DYNhelp,231) = DYNX(W_,84)-DYNX(Y_,0);
DYNX(DYNhelp,232) = fabs(DYNX(Y_,0)-DYNX(W_,183));
whenModelica(LessEqualMinor(DYNX(DYNhelp,230),"abs(Efd-sT5B.simpleLagLimVar.outMax)",
   1E-15,"1E-15", 16) AND LessMinor(DYNX(DYNhelp,231),"sT5B.VERR2.y-Efd", 0,"0",
   17) OR LessEqualMinor(DYNX(DYNhelp,232),"abs(Efd-sT5B.simpleLagLimVar.outMin)",
   1E-15,"1E-15", 18) AND GreaterMinor(DYNX(DYNhelp,231),"sT5B.VERR2.y-Efd", 0,
  "0", 19), 0) 
  reinitNew(DYNX(X_,6), DYNX(Y_,0), DYNX(DYNhelp,233), DYNX(did_->helpvari_vec,138));
endwhenModelica()
endwhenBlock


/* End of reinit equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [VA|MVA]", 0, 30000000, 0.0,0.0,0.0,\
0,560)
DeclareParameter("SysData.fn", "System frequency [Hz]", 1, 50, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xd", "", 2, 1.183, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.R_a", "", 3, 0.004799183673469388, 0.0,0.0,\
0.0,0,560)
DeclareParameter("machineData.data.H", "", 4, 2.137, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.D", "", 5, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xpd", "", 6, 0.371, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xppd", "", 7, 0.215, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xppq", "", 8, 0.241, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xq", "", 9, 0.62, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tpd0", "", 10, 3.77, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tppd0", "", 11, 0.0552, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Tppq0", "", 12, 0.0823, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Xl", "", 13, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.S10", "", 14, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.S12", "", 15, 0.4, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_0", "", 16, 0.9745, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.A_0", "", 17, -15, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.P_0", "", 18, 4996435.71, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.Q_0", "", 19, -2475000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_R", "[s]", 20, 0.012, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_C1", "[s]", 21, 0.85, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_B1", "[s]", 22, 32.85, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_C2", "[s]", 23, 0.025302356, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_B2", "[s]", 24, 0.0460734, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_R", "[1]", 25, 500.6942, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_RMAX", "[1]", 26, 4.35, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_RMIN", "[1]", 27, -3.825, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_1_AVR", "[s]", 28, 0.0060734, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_C", "[1]", 29, 0.99, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UC1", "[s]", 30, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UB1", "[s]", 31, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UC2", "[s]", 32, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_UB2", "[s]", 33, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OC1", "[s]", 34, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OB1", "[s]", 35, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OC2", "[s]", 36, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_OB2", "[s]", 37, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w1", "", 38, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w2", "", 39, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_6", "", 40, 1E-09, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w3", "", 41, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_w4", "", 42, 1E-09, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_7", "", 43, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S2", "", 44, 0.99, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S3", "", 45, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_8", "", 46, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_9", "", 47, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.K_S1", "", 48, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_1", "", 49, 0.15, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_2", "", 50, 0.025, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_3", "", 51, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_4", "", 52, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_10", "", 53, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.T_11", "", 54, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S1MAX", "", 55, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S1MIN", "", 56, -0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S2MAX", "", 57, 1.25, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_S2MIN", "", 58, -1.25, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_STMAX", "", 59, 0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.V_STMIN", "", 60, -0.1, 0.0,0.0,0.0,0,560)
DeclareParameter("machineData.data.M", "[:#(type=Integer)]", 61, 1, 0.0,0.0,0.0,\
0,564)
DeclareParameter("machineData.data.N", "[:#(type=Integer)]", 62, 1, 0.0,0.0,0.0,\
0,564)
DeclareParameter("const1.k", "Constant output value", 63, -1E+60, 0.0,0.0,0.0,0,560)
DeclareAlias2("const1.y", "Connector of Real output signal", "const1.k", 1, 7, 63,\
 0)
DeclareParameter("const2.k", "Constant output value", 64, 1E+60, 0.0,0.0,0.0,0,560)
DeclareAlias2("const2.y", "Connector of Real output signal", "const2.k", 1, 7, 64,\
 0)
DeclareAlias2("sT5B.VUEL", "", "const1.k", 1, 7, 63, 0)
DeclareAlias2("sT5B.VOEL", "", "const2.k", 1, 7, 64, 0)
DeclareAlias2("sT5B.EFD", "Excitation Voltage (pu) [1]", "Efd", 1, 3, 0, 0)
DeclareAlias2("sT5B.EFD0", "[1]", "const3.k", 1, 7, 104, 0)
DeclareAlias2("sT5B.VOTHSG", "", "const4.k", 1, 7, 103, 0)
DeclareAlias2("sT5B.ECOMP", "[1]", "V", 1, 2, 0, 0)
DeclareVariable("sT5B.VoltageReference.k", "Constant output value [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.VoltageReference.y", "Connector of Real output signal [1]", \
"sT5B.VoltageReference.k", 1, 5, 0, 0)
DeclareAlias2("sT5B.DiffV.u1", "Connector of Real input signal 1 [1]", \
"sT5B.VoltageReference.k", 1, 5, 0, 0)
DeclareVariable("sT5B.DiffV.u2", "Connector of Real input signal 2 [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.DiffV.y", "Connector of Real output signal", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("sT5B.DiffV.k1", "Gain of input signal 1", 65, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.DiffV.k2", "Gain of input signal 2", 66, -1, 0.0,0.0,0.0,\
0,560)
DeclareVariable("sT5B.Efd0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("sT5B.V_REF", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("sT5B.ECOMP0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("sT5B.XADIFD", "", "Ifd", 1, 2, 1, 0)
DeclareVariable("sT5B.T_R", "Regulator input filter time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_C1", "Voltage regulator numerator (lead) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_B1", "Voltage regulator denominator (lag) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_C2", "Voltage regulator numerator (lead) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_B2", "Voltage regulator denominator (lag) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.K_R", "Voltage regulator gain [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.V_RMAX", "Maximum regulator output [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("sT5B.V_RMIN", "Minimum regulator output [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("sT5B.T_1", "Thyristor bridge firing control equivalent time constant [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.K_C", "Rectifier loading factor proportional to commutating reactance [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_UC1", "UEL regulator numerator (lead) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_UB1", "UEL regulator denominator (lag) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_UC2", "UEL regulator numerator (lead) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_UB2", "UEL regulator denominator (lag) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_OC1", "OEL regulator numerator (lead) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_OB1", "OEL regulator denominator (lag) time constant (first block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_OC2", "OEL regulator numerator (lead) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.T_OB2", "OEL regulator denominator (lag) time constant (second block) [s]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.VERR1.u1", "Connector of Real input signal 1", "const4.k", 1,\
 7, 103, 0)
DeclareVariable("sT5B.VERR1.u2", "Connector of Real input signal 2", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.VERR1.y", "Connector of Real output signal", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("sT5B.VERR1.k1", "Gain of input signal 1", 67, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.VERR1.k2", "Gain of input signal 2", 68, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("sT5B.lV_Gate.n1", "", "const2.k", 1, 7, 64, 0)
DeclareVariable("sT5B.lV_Gate.n2", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.lV_Gate.p", "", "sT5B.VERR1.u2", 1, 5, 24, 0)
DeclareAlias2("sT5B.hV_Gate.n1", "", "const1.k", 1, 7, 63, 0)
DeclareAlias2("sT5B.hV_Gate.n2", "", "sT5B.DiffV.y", 1, 5, 2, 0)
DeclareAlias2("sT5B.hV_Gate.p", "", "sT5B.lV_Gate.n2", 1, 5, 26, 0)
DeclareAlias2("sT5B.imLimitedLeadLag.u", "Connector of Real input signal", \
"sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag.K", "Gain", 69, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.y_start", "Output start value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag.add2.u1", "Connector of Real input signal 1",\
 "sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag.add2.k1", "Gain of input signal 1", 70, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag.add2.k2", "Gain of input signal 2", 71, 1,\
 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag.add2.y", 1, 5, 34, 0)
DeclareVariable("sT5B.imLimitedLeadLag.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag.y", 1, 5, 27, 0)
DeclareAlias2("sT5B.imLimitedLeadLag.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag.integrator.y", 1, 1, 0, 0)
DeclareVariable("sT5B.imLimitedLeadLag.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag.add3.k1", "Gain of input signal 1", 72, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag.add3.k2", "Gain of input signal 2", 73, -1,\
 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.k", "Integrator gain [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag.add3.y", 1, 5, 37, 0)
DeclareState("sT5B.imLimitedLeadLag.integrator.y", "Connector of Real output signal [1]",\
 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.local_reset", "[:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag.integrator.local_set", "", 0, 0.0,0.0,0.0,\
0,1537)
DeclareVariable("sT5B.imLimitedLeadLag.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag.integrator.y", 1, 1, 0, 0)
DeclareAlias2("sT5B.imLimitedLeadLag.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag.add2.u2", 1, 5, 33, 0)
DeclareVariable("sT5B.imLimitedLeadLag.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag.gain.y", 1, 5, 36, 0)
DeclareAlias2("sT5B.imLimitedLeadLag.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag.y", 1, 5, 27, 0)
DeclareAlias2("sT5B.imLimitedLeadLag.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag.gain.y", 1, 5, 36, 1024)
DeclareAlias2("sT5B.imLimitedLeadLag2.u", "Connector of Real input signal [1]", \
"sT5B.imLimitedLeadLag.y", 1, 5, 27, 0)
DeclareVariable("sT5B.imLimitedLeadLag2.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag2.K", "Gain", 74, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag2.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.y_start", "Output start value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag2.add2.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag.y", 1, 5, 27, 0)
DeclareVariable("sT5B.imLimitedLeadLag2.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag2.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag2.add2.k1", "Gain of input signal 1", 75,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag2.add2.k2", "Gain of input signal 2", 76,\
 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag2.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag2.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag2.add2.y", 1, 5, 58, 0)
DeclareVariable("sT5B.imLimitedLeadLag2.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag2.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag2.y", 1, 5, 51, 0)
DeclareAlias2("sT5B.imLimitedLeadLag2.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag2.integrator.y", 1, 1, 1, 0)
DeclareVariable("sT5B.imLimitedLeadLag2.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag2.add3.k1", "Gain of input signal 1", 77,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag2.add3.k2", "Gain of input signal 2", 78,\
 -1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.k", "Integrator gain [1]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag2.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag2.add3.y", 1, 5, 61, 0)
DeclareState("sT5B.imLimitedLeadLag2.integrator.y", "Connector of Real output signal [1]",\
 1, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag2.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.local_reset", \
"[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag2.integrator.local_set", "", 0, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("sT5B.imLimitedLeadLag2.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag2.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag2.integrator.y", 1, 1, 1, 0)
DeclareAlias2("sT5B.imLimitedLeadLag2.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag2.add2.u2", 1, 5, 57, 0)
DeclareVariable("sT5B.imLimitedLeadLag2.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag2.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag2.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag2.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag2.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag2.gain.y", 1, 5, 60, 0)
DeclareAlias2("sT5B.imLimitedLeadLag2.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag2.y", 1, 5, 51, 0)
DeclareAlias2("sT5B.imLimitedLeadLag2.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag2.gain.y", 1, 5, 60, 1024)
DeclareVariable("sT5B.K_r.k", "Gain value multiplied with input signal [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.K_r.u", "Input signal connector [1]", "sT5B.imLimitedLeadLag2.y", 1,\
 5, 51, 0)
DeclareVariable("sT5B.K_r.y", "Output signal connector [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.limiter.uMax", "Upper limits of input signals [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.limiter.uMin", "Lower limits of input signals [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.limiter.u", "Connector of Real input signal [1]", \
"sT5B.K_r.y", 1, 5, 76, 0)
DeclareVariable("sT5B.limiter.y", "Connector of Real output signal [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.K_r.y", 1, 5, 76, 1024)
DeclareVariable("sT5B.VERR2.u1", "Connector of Real input signal 1", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.VERR2.u2", "Connector of Real input signal 2 [1]", \
"sT5B.limiter.y", 1, 5, 82, 0)
DeclareVariable("sT5B.VERR2.y", "Connector of Real output signal [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.VERR2.k1", "Gain of input signal 1", 79, -1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("sT5B.VERR2.k2", "Gain of input signal 2", 80, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.K_c.k", "Gain value multiplied with input signal [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.K_c.u", "Input signal connector", "Ifd", 1, 2, 1, 0)
DeclareAlias2("sT5B.K_c.y", "Output signal connector", "sT5B.VERR2.u1", 1, 5, 83,\
 0)
DeclareAlias2("sT5B.imLimitedLeadLag1.u", "Connector of Real input signal", \
"sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag1.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag1.K", "Gain", 81, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag1.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.y_start", "Output start value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag1.add2.u1", "Connector of Real input signal 1",\
 "sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag1.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag1.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag1.add2.k1", "Gain of input signal 1", 82,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag1.add2.k2", "Gain of input signal 2", 83,\
 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag1.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag1.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag1.add2.y", 1, 5, 93, 0)
DeclareVariable("sT5B.imLimitedLeadLag1.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag1.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag1.y", 1, 5, 86, 0)
DeclareAlias2("sT5B.imLimitedLeadLag1.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag1.integrator.y", 1, 1, 2, 0)
DeclareVariable("sT5B.imLimitedLeadLag1.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag1.add3.k1", "Gain of input signal 1", 84,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag1.add3.k2", "Gain of input signal 2", 85,\
 -1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.k", "Integrator gain [1]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag1.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag1.add3.y", 1, 5, 96, 0)
DeclareState("sT5B.imLimitedLeadLag1.integrator.y", "Connector of Real output signal [1]",\
 2, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag1.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.local_reset", \
"[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag1.integrator.local_set", "", 0, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("sT5B.imLimitedLeadLag1.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag1.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag1.integrator.y", 1, 1, 2, 0)
DeclareAlias2("sT5B.imLimitedLeadLag1.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag1.add2.u2", 1, 5, 92, 0)
DeclareVariable("sT5B.imLimitedLeadLag1.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag1.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag1.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag1.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag1.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag1.gain.y", 1, 5, 95, 0)
DeclareAlias2("sT5B.imLimitedLeadLag1.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag1.y", 1, 5, 86, 0)
DeclareAlias2("sT5B.imLimitedLeadLag1.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag1.gain.y", 1, 5, 95, 1024)
DeclareAlias2("sT5B.imLimitedLeadLag3.u", "Connector of Real input signal [1]", \
"sT5B.imLimitedLeadLag1.y", 1, 5, 86, 0)
DeclareVariable("sT5B.imLimitedLeadLag3.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag3.K", "Gain", 86, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag3.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.y_start", "Output start value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag3.add2.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag1.y", 1, 5, 86, 0)
DeclareVariable("sT5B.imLimitedLeadLag3.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag3.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag3.add2.k1", "Gain of input signal 1", 87,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag3.add2.k2", "Gain of input signal 2", 88,\
 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag3.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag3.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag3.add2.y", 1, 5, 117, 0)
DeclareVariable("sT5B.imLimitedLeadLag3.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag3.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag3.y", 1, 5, 110, 0)
DeclareAlias2("sT5B.imLimitedLeadLag3.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag3.integrator.y", 1, 1, 3, 0)
DeclareVariable("sT5B.imLimitedLeadLag3.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag3.add3.k1", "Gain of input signal 1", 89,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag3.add3.k2", "Gain of input signal 2", 90,\
 -1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.k", "Integrator gain [1]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag3.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag3.add3.y", 1, 5, 120, 0)
DeclareState("sT5B.imLimitedLeadLag3.integrator.y", "Connector of Real output signal [1]",\
 3, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag3.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.local_reset", \
"[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag3.integrator.local_set", "", 0, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("sT5B.imLimitedLeadLag3.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag3.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag3.integrator.y", 1, 1, 3, 0)
DeclareAlias2("sT5B.imLimitedLeadLag3.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag3.add2.u2", 1, 5, 116, 0)
DeclareVariable("sT5B.imLimitedLeadLag3.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag3.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag3.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag3.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag3.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag3.gain.y", 1, 5, 119, 0)
DeclareAlias2("sT5B.imLimitedLeadLag3.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag3.y", 1, 5, 110, 0)
DeclareAlias2("sT5B.imLimitedLeadLag3.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag3.gain.y", 1, 5, 119, 1024)
DeclareAlias2("sT5B.imLimitedLeadLag4.u", "Connector of Real input signal", \
"sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag4.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag4.K", "Gain", 91, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag4.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.y_start", "Output start value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag4.add2.u1", "Connector of Real input signal 1",\
 "sT5B.VERR1.y", 1, 5, 25, 0)
DeclareVariable("sT5B.imLimitedLeadLag4.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag4.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag4.add2.k1", "Gain of input signal 1", 92,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag4.add2.k2", "Gain of input signal 2", 93,\
 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag4.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag4.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag4.add2.y", 1, 5, 141, 0)
DeclareVariable("sT5B.imLimitedLeadLag4.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag4.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag4.y", 1, 5, 134, 0)
DeclareAlias2("sT5B.imLimitedLeadLag4.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag4.integrator.y", 1, 1, 4, 0)
DeclareVariable("sT5B.imLimitedLeadLag4.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag4.add3.k1", "Gain of input signal 1", 94,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag4.add3.k2", "Gain of input signal 2", 95,\
 -1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.k", "Integrator gain [1]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag4.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag4.add3.y", 1, 5, 144, 0)
DeclareState("sT5B.imLimitedLeadLag4.integrator.y", "Connector of Real output signal [1]",\
 4, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag4.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.local_reset", \
"[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag4.integrator.local_set", "", 0, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("sT5B.imLimitedLeadLag4.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag4.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag4.integrator.y", 1, 1, 4, 0)
DeclareAlias2("sT5B.imLimitedLeadLag4.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag4.add2.u2", 1, 5, 140, 0)
DeclareVariable("sT5B.imLimitedLeadLag4.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag4.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag4.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag4.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag4.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag4.gain.y", 1, 5, 143, 0)
DeclareAlias2("sT5B.imLimitedLeadLag4.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag4.y", 1, 5, 134, 0)
DeclareAlias2("sT5B.imLimitedLeadLag4.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag4.gain.y", 1, 5, 143, 1024)
DeclareAlias2("sT5B.imLimitedLeadLag5.u", "Connector of Real input signal [1]", \
"sT5B.imLimitedLeadLag4.y", 1, 5, 134, 0)
DeclareVariable("sT5B.imLimitedLeadLag5.y", "Connector of Real output signal [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag5.K", "Gain", 96, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag5.T1", "Lead time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.T2", "Lag time constant [s]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.outMax", "Maximum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.outMin", "Minimum output value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.y_start", "Output start value [1]", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag5.add2.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag4.y", 1, 5, 134, 0)
DeclareVariable("sT5B.imLimitedLeadLag5.add2.u2", "Connector of Real input signal 2 [1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag5.add2.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag5.add2.k1", "Gain of input signal 1", 97,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag5.add2.k2", "Gain of input signal 2", 98,\
 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag5.gain.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag5.gain.u", "Input signal connector", \
"sT5B.imLimitedLeadLag5.add2.y", 1, 5, 165, 0)
DeclareVariable("sT5B.imLimitedLeadLag5.gain.y", "Output signal connector [1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.imLimitedLeadLag5.add3.u1", "Connector of Real input signal 1 [1]",\
 "sT5B.imLimitedLeadLag5.y", 1, 5, 158, 0)
DeclareAlias2("sT5B.imLimitedLeadLag5.add3.u2", "Connector of Real input signal 2 [1]",\
 "sT5B.imLimitedLeadLag5.integrator.y", 1, 1, 5, 0)
DeclareVariable("sT5B.imLimitedLeadLag5.add3.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.imLimitedLeadLag5.add3.k1", "Gain of input signal 1", 99,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("sT5B.imLimitedLeadLag5.add3.k2", "Gain of input signal 2", 100,\
 -1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.k", "Integrator gain [1]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.use_reset", "=true, if reset port enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.use_set", "=true, if set port enabled and used as reinitialization value when reset [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.initType", "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.y_start", "Initial or guess value of output (= state) [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag5.integrator.u", "Connector of Real input signal",\
 "sT5B.imLimitedLeadLag5.add3.y", 1, 5, 168, 0)
DeclareState("sT5B.imLimitedLeadLag5.integrator.y", "Connector of Real output signal [1]",\
 5, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.imLimitedLeadLag5.integrator.der(y)", "der(Connector of Real output signal) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.local_reset", \
"[:#(type=Boolean)]", false, 0.0,0.0,0.0,0,1539)
DeclareVariable("sT5B.imLimitedLeadLag5.integrator.local_set", "", 0, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("sT5B.imLimitedLeadLag5.gain1.k", "Gain value multiplied with input signal [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.imLimitedLeadLag5.gain1.u", "Input signal connector [1]", \
"sT5B.imLimitedLeadLag5.integrator.y", 1, 1, 5, 0)
DeclareAlias2("sT5B.imLimitedLeadLag5.gain1.y", "Output signal connector [1]", \
"sT5B.imLimitedLeadLag5.add2.u2", 1, 5, 164, 0)
DeclareVariable("sT5B.imLimitedLeadLag5.limiter.uMax", "Upper limits of input signals [1]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.limiter.uMin", "Lower limits of input signals [1]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.imLimitedLeadLag5.limiter.strict", "= true, if strict limits with noEvent(..) [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sT5B.imLimitedLeadLag5.limiter.homotopyType", "Simplified model for homotopy-based initialization [:#(type=Modelica.Blocks.Types.LimiterHomotopy)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sT5B.imLimitedLeadLag5.limiter.limitsAtInit", "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator) [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareAlias2("sT5B.imLimitedLeadLag5.limiter.u", "Connector of Real input signal [1]",\
 "sT5B.imLimitedLeadLag5.gain.y", 1, 5, 167, 0)
DeclareAlias2("sT5B.imLimitedLeadLag5.limiter.y", "Connector of Real output signal [1]",\
 "sT5B.imLimitedLeadLag5.y", 1, 5, 158, 0)
DeclareAlias2("sT5B.imLimitedLeadLag5.limiter.simplifiedExpr", "Simplified expression for homotopy-based initialization [1]",\
 "sT5B.imLimitedLeadLag5.gain.y", 1, 5, 167, 1024)
DeclareAlias2("sT5B.simpleLagLimVar.u", "Connector of Real input signal [1]", \
"sT5B.VERR2.y", 1, 5, 84, 0)
DeclareAlias2("sT5B.simpleLagLimVar.y", "Connector of Real output signal [1]", \
"Efd", 1, 3, 0, 0)
DeclareVariable("sT5B.simpleLagLimVar.outMax", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.simpleLagLimVar.outMin", "[1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("sT5B.simpleLagLimVar.const.y", "Value of Real output [s]", \
"sT5B.simpleLagLimVar.T", 1, 5, 184, 0)
DeclareParameter("sT5B.simpleLagLimVar.K", "Gain", 101, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.simpleLagLimVar.T", "Lag time constant [s]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("sT5B.simpleLagLimVar.y_start", "Output start value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.simpleLagLimVar.T_mod", "[s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareState("sT5B.simpleLagLimVar.state", "[1]", 6, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.simpleLagLimVar.der(state)", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("sT5B.high.k", "Gain value multiplied with input signal [1]", 1,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.high.u", "Input signal connector [1]", "V", 1, 2, 0, 0)
DeclareAlias2("sT5B.high.y", "Output signal connector [1]", "sT5B.simpleLagLimVar.outMax", 1,\
 5, 182, 0)
DeclareVariable("sT5B.low.k", "Gain value multiplied with input signal [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("sT5B.low.u", "Input signal connector [1]", "V", 1, 2, 0, 0)
DeclareAlias2("sT5B.low.y", "Output signal connector [1]", "sT5B.simpleLagLimVar.outMin", 1,\
 5, 183, 0)
DeclareAlias2("sT5B.TransducerDelay.u", "Connector of Real input signal [1]", \
"V", 1, 2, 0, 0)
DeclareAlias2("sT5B.TransducerDelay.y", "Connector of Real output signal [1]", \
"sT5B.DiffV.u2", 1, 5, 1, 0)
DeclareAlias2("sT5B.TransducerDelay.const.y", "Value of Real output [s]", \
"sT5B.TransducerDelay.T", 1, 5, 189, 0)
DeclareState("sT5B.TransducerDelay.state", "[1]", 7, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("sT5B.TransducerDelay.der(state)", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sT5B.TransducerDelay.K", "Gain", 102, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("sT5B.TransducerDelay.T", "Lag time constant [s]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("sT5B.TransducerDelay.y_start", "Output start value [1]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("sT5B.TransducerDelay.T_mod", "[s]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("sT5B.VR0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareParameter("const4.k", "Constant output value", 103, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("const4.y", "Connector of Real output signal", "const4.k", 1, 7, 103,\
 0)
DeclareParameter("const3.k", "Constant output value [1]", 104, 0.332057384, \
0.0,0.0,0.0,0,560)
DeclareAlias2("const3.y", "Connector of Real output signal [1]", "const3.k", 1, 7,\
 104, 0)
DeclareOutput("Efd", "[1]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("V", "[1:#(prefix=input)]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("Ifd", "[:#(prefix=input)]", 1, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void DelayedUpdateReinit(double*time, double* X_, double* W_, double* U_, double* Y_, struct DYNInstanceData*did_) {
if (DYNX(did_->helpvari_vec,138)) {
  DYNX(X_,6)=DYNX(DYNhelp,233);
  DYNX(did_->helpvari_vec,138)=0;
}
}
DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
if (initialCall) DYNX(did_->xInitial_var, 0)=DYNX(X_,0);
else if (DYNHReject) DYNX(X_,0)=did_->xInitial_var2[0]; else did_->xInitial_var2[0]=
  DYNX(X_,0);
if (initialCall) DYNX(did_->xInitial_var, 2)=DYNX(X_,2);
else if (DYNHReject) DYNX(X_,2)=did_->xInitial_var2[2]; else did_->xInitial_var2[2]=
  DYNX(X_,2);
if (initialCall) DYNX(did_->xInitial_var, 1)=DYNX(X_,1);
else if (DYNHReject) DYNX(X_,1)=did_->xInitial_var2[1]; else did_->xInitial_var2[1]=
  DYNX(X_,1);
if (initialCall) DYNX(did_->xInitial_var, 3)=DYNX(X_,3);
else if (DYNHReject) DYNX(X_,3)=did_->xInitial_var2[3]; else did_->xInitial_var2[3]=
  DYNX(X_,3);
if (initialCall) DYNX(did_->xInitial_var, 4)=DYNX(X_,4);
else if (DYNHReject) DYNX(X_,4)=did_->xInitial_var2[4]; else did_->xInitial_var2[4]=
  DYNX(X_,4);
if (initialCall) DYNX(did_->xInitial_var, 5)=DYNX(X_,5);
else if (DYNHReject) DYNX(X_,5)=did_->xInitial_var2[5]; else did_->xInitial_var2[5]=
  DYNX(X_,5);
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(F_,7), 0.0, 0);
DoRemember_(DYNX(F_,6), 0.0, 1);
EndEqBlock
UpdateQEvaluate(1)
EndDataBlock
  BreakSectionStart(1);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[1] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,0) = DYNX(W_,35)*DYNX(DP_,72);
  DYNX(DYNhelp,1) = DYNX(DP_,70)*DYNX(W_,25);
  DYNX(X_,0) = DYNX(W_,42);
  SolveScalarLinearParametric( -(DYNX(DP_,73)+DYNX(DP_,71)*DYNX(DYNhelp,0)*
    DYNX(W_,45))," -(sT5B.imLimitedLeadLag.add3.k2+sT5B.imLimitedLeadLag.add2.k2*(sT5B.imLimitedLeadLag.gain.k*sT5B.imLimitedLeadLag.add3.k1)*sT5B.imLimitedLeadLag.gain1.k)",
     DYNX(DYNhelp,0)*DYNX(DYNhelp,1)-DYNX(W_,37),"sT5B.imLimitedLeadLag.gain.k*sT5B.imLimitedLeadLag.add3.k1*(sT5B.imLimitedLeadLag.add2.k1*sT5B.VERR1.y)-sT5B.imLimitedLeadLag.add3.y",
     DYNX(X_,0),"sT5B.imLimitedLeadLag.integrator.y");
  DYNX(W_,33) = DYNX(W_,45)*DYNX(X_,0);
  DYNX(W_,34) = DYNX(DYNhelp,1)+DYNX(DP_,71)*DYNX(W_,33);
  DYNX(W_,27) = DYNX(W_,35)*DYNX(W_,34);
   /* End of Equation Block */ 

  DYNX(W_,36) = DYNX(W_,27);
  BreakSectionEnd()
  BreakSectionStart(3);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[2] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,38) = DYNX(W_,59)*DYNX(DP_,77);
  DYNX(DYNhelp,39) = DYNX(DP_,75)*DYNX(W_,27);
  DYNX(X_,1) = DYNX(W_,66);
  SolveScalarLinearParametric( -(DYNX(DP_,78)+DYNX(DP_,76)*DYNX(DYNhelp,38)*
    DYNX(W_,69))," -(sT5B.imLimitedLeadLag2.add3.k2+sT5B.imLimitedLeadLag2.add2.k2*(sT5B.imLimitedLeadLag2.gain.k*sT5B.imLimitedLeadLag2.add3.k1)*sT5B.imLimitedLeadLag2.gain1.k)",
     DYNX(DYNhelp,38)*DYNX(DYNhelp,39)-DYNX(W_,61),"sT5B.imLimitedLeadLag2.gain.k*sT5B.imLimitedLeadLag2.add3.k1*(sT5B.imLimitedLeadLag2.add2.k1*sT5B.imLimitedLeadLag.y)-sT5B.imLimitedLeadLag2.add3.y",
     DYNX(X_,1),"sT5B.imLimitedLeadLag2.integrator.y");
  DYNX(W_,57) = DYNX(W_,69)*DYNX(X_,1);
  DYNX(W_,58) = DYNX(DYNhelp,39)+DYNX(DP_,76)*DYNX(W_,57);
  DYNX(W_,51) = DYNX(W_,59)*DYNX(W_,58);
   /* End of Equation Block */ 

  DYNX(W_,60) = DYNX(W_,51);
  BreakSectionEnd()
  BreakSectionStart(4);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[3] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,76) = DYNX(W_,94)*DYNX(DP_,84);
  DYNX(DYNhelp,77) = DYNX(DP_,82)*DYNX(W_,25);
  DYNX(X_,2) = DYNX(W_,101);
  SolveScalarLinearParametric( -(DYNX(DP_,85)+DYNX(DP_,83)*DYNX(DYNhelp,76)*
    DYNX(W_,104))," -(sT5B.imLimitedLeadLag1.add3.k2+sT5B.imLimitedLeadLag1.add2.k2*(sT5B.imLimitedLeadLag1.gain.k*sT5B.imLimitedLeadLag1.add3.k1)*sT5B.imLimitedLeadLag1.gain1.k)",
     DYNX(DYNhelp,76)*DYNX(DYNhelp,77)-DYNX(W_,96),"sT5B.imLimitedLeadLag1.gain.k*sT5B.imLimitedLeadLag1.add3.k1*(sT5B.imLimitedLeadLag1.add2.k1*sT5B.VERR1.y)-sT5B.imLimitedLeadLag1.add3.y",
     DYNX(X_,2),"sT5B.imLimitedLeadLag1.integrator.y");
  DYNX(W_,92) = DYNX(W_,104)*DYNX(X_,2);
  DYNX(W_,93) = DYNX(DYNhelp,77)+DYNX(DP_,83)*DYNX(W_,92);
  DYNX(W_,86) = DYNX(W_,94)*DYNX(W_,93);
   /* End of Equation Block */ 

  DYNX(W_,95) = DYNX(W_,86);
  BreakSectionEnd()
  BreakSectionStart(5);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[4] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,114) = DYNX(W_,118)*DYNX(DP_,89);
  DYNX(DYNhelp,115) = DYNX(DP_,87)*DYNX(W_,86);
  DYNX(X_,3) = DYNX(W_,125);
  SolveScalarLinearParametric( -(DYNX(DP_,90)+DYNX(DP_,88)*DYNX(DYNhelp,114)*
    DYNX(W_,128))," -(sT5B.imLimitedLeadLag3.add3.k2+sT5B.imLimitedLeadLag3.add2.k2*(sT5B.imLimitedLeadLag3.gain.k*sT5B.imLimitedLeadLag3.add3.k1)*sT5B.imLimitedLeadLag3.gain1.k)",
     DYNX(DYNhelp,114)*DYNX(DYNhelp,115)-DYNX(W_,120),"sT5B.imLimitedLeadLag3.gain.k*sT5B.imLimitedLeadLag3.add3.k1*(sT5B.imLimitedLeadLag3.add2.k1*sT5B.imLimitedLeadLag1.y)-sT5B.imLimitedLeadLag3.add3.y",
     DYNX(X_,3),"sT5B.imLimitedLeadLag3.integrator.y");
  DYNX(W_,116) = DYNX(W_,128)*DYNX(X_,3);
  DYNX(W_,117) = DYNX(DYNhelp,115)+DYNX(DP_,88)*DYNX(W_,116);
  DYNX(W_,110) = DYNX(W_,118)*DYNX(W_,117);
   /* End of Equation Block */ 

  DYNX(W_,119) = DYNX(W_,110);
  BreakSectionEnd()
  BreakSectionStart(6);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[5] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,152) = DYNX(W_,142)*DYNX(DP_,94);
  DYNX(DYNhelp,153) = DYNX(DP_,92)*DYNX(W_,25);
  DYNX(X_,4) = DYNX(W_,149);
  SolveScalarLinearParametric( -(DYNX(DP_,95)+DYNX(DP_,93)*DYNX(DYNhelp,152)*
    DYNX(W_,152))," -(sT5B.imLimitedLeadLag4.add3.k2+sT5B.imLimitedLeadLag4.add2.k2*(sT5B.imLimitedLeadLag4.gain.k*sT5B.imLimitedLeadLag4.add3.k1)*sT5B.imLimitedLeadLag4.gain1.k)",
     DYNX(DYNhelp,152)*DYNX(DYNhelp,153)-DYNX(W_,144),"sT5B.imLimitedLeadLag4.gain.k*sT5B.imLimitedLeadLag4.add3.k1*(sT5B.imLimitedLeadLag4.add2.k1*sT5B.VERR1.y)-sT5B.imLimitedLeadLag4.add3.y",
     DYNX(X_,4),"sT5B.imLimitedLeadLag4.integrator.y");
  DYNX(W_,140) = DYNX(W_,152)*DYNX(X_,4);
  DYNX(W_,141) = DYNX(DYNhelp,153)+DYNX(DP_,93)*DYNX(W_,140);
  DYNX(W_,134) = DYNX(W_,142)*DYNX(W_,141);
   /* End of Equation Block */ 

  DYNX(W_,143) = DYNX(W_,134);
  BreakSectionEnd()
  BreakSectionStart(7);

   /* Linear system of equations to solve. */
  /* Tag: simplified homotopy initialization.linear[6] */
  /* Introducing 2 common subexpressions used in 2 expressions */
  /* Of the common subexpressions 2 are reals, 0 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,190) = DYNX(W_,166)*DYNX(DP_,99);
  DYNX(DYNhelp,191) = DYNX(DP_,97)*DYNX(W_,134);
  DYNX(X_,5) = DYNX(W_,173);
  SolveScalarLinearParametric( -(DYNX(DP_,100)+DYNX(DP_,98)*DYNX(DYNhelp,190)*
    DYNX(W_,176))," -(sT5B.imLimitedLeadLag5.add3.k2+sT5B.imLimitedLeadLag5.add2.k2*(sT5B.imLimitedLeadLag5.gain.k*sT5B.imLimitedLeadLag5.add3.k1)*sT5B.imLimitedLeadLag5.gain1.k)",
     DYNX(DYNhelp,190)*DYNX(DYNhelp,191)-DYNX(W_,168),"sT5B.imLimitedLeadLag5.gain.k*sT5B.imLimitedLeadLag5.add3.k1*(sT5B.imLimitedLeadLag5.add2.k1*sT5B.imLimitedLeadLag4.y)-sT5B.imLimitedLeadLag5.add3.y",
     DYNX(X_,5),"sT5B.imLimitedLeadLag5.integrator.y");
  DYNX(W_,164) = DYNX(W_,176)*DYNX(X_,5);
  DYNX(W_,165) = DYNX(DYNhelp,191)+DYNX(DP_,98)*DYNX(W_,164);
  DYNX(W_,158) = DYNX(W_,166)*DYNX(W_,165);
   /* End of Equation Block */ 

  DYNX(W_,167) = DYNX(W_,158);
  BreakSectionEnd()

BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(2);
BreakSectionFunctionEnd()
