
clear
close all

Ts=0.005;

%%%%%% Definition of the model for the grey-box identification

odefun = 'AVR_greyest';

%%%% True parameters

Tr0 = 0.01;
Tc10 = 1.49432157800359;
Tb10 = 20.00657894736842105;
Tc20 = 0.00362976406533575;
Tb20 = 0.00657894736842105;
Kr0 = 200;
T10 = 0.00657894736842105;
Kc0 = 0.3997207818109294;



parameters0 = {'Tr',Tr0;'Tc1',Tc10;'Tb1',Tb10;'Tc2',Tc20;'Tb2',Tb20;'Kr',Kr0;'T1',T10;'Kc',Kc0};

fcn_type = 'c';

sys_true = idgrey(odefun,parameters0,fcn_type); %%% True system

%%%%% Parameters that will be used for the initialization of the grey-box
%%%%% identification 

aa=2;

Tr = 0.01 *aa;
Tc1 = 1.49432157800359*aa;
Tb1 = 20.00657894736842105*aa;
Tc2 = 0.00362976406533575*aa;
Tb2 = 0.00657894736842105*aa;
Kr = 200*aa;
T1 = 0.00657894736842105*aa;
Kc = 0.3997207818109294*aa;

parameters = {'Tr',Tr;'Tc1',Tc1;'Tb1',Tb1;'Tc2',Tc2;'Tb2',Tb2;'Kr',Kr;'T1',T1;'Kc',Kc};

sys_init = idgrey(odefun,parameters,fcn_type); %%%% system for the initialization of the grey-box identification


%%%%%%%% Generation of the data
%% load model from simulink diagram
 
 load ST5B_data.mat
 load Capacitive_simulation
 mdl = 'ST5B';
 % add in additional parameters for simulation
 Efd_plot = [time,Efd];
    Tr = 0.01;
    Tb1 = 2;
    Tc1 = 20;
    Tb2 = 0.02;
    Tc2 = 0.005;
    Kr = 500;
    T1 = 0.005;
    Kc = 1;
    Vrmax = 4.35;
    Vrmin = -3.825;
    Efd0 = Efd(1);
    XadIfd = Ifd(1);
    Vinit = V(1);
    PSS= 0;
    VR0 = Efd0 + Kc*XadIfd;
 %%
%%%% Generation of the data using the simulator using only V as excitation
 %%%% to observe the informativity problem
  set_param(mdl,'SimulationCommand','Start') 
  pause(2)
  V = V - mean(V(1:60));
  Ifd = Ifd - mean(Ifd(1:60));
  Efd_sim = out.Efd.data - mean(out.Efd.data(1:60));
 

 
 meas_noise=0*randn(size(time));  %possibility of adding measurement noise on Efd; here supposed equal to zero
 data=iddata(Efd_sim,[V Ifd],Ts);
   

   
%%%% grey-box identification using the data generated by V   
opt = greyestOptions;
opt.InitialState = 'zero';
opt.Display = 'on';  
modelv = greyest(data,sys_init,opt);
  
figure(1); bode(modelv,'r',sys_true,'b',logspace(-3,2.79,200));  
figure(2); compare(modelv,data);

%%%% We observe a large discrepancy between identified model and true
%%%% system while we have a perfect fit --> informativity issue. Note that the
%%%% transfer function from Ifd to Efd in the identified model has a positive gain while it is negative in reality !!!! 

%%
%%%% Further verification of the informativity problem. Condition (7) in my note is not respected 
 load exc_r  %excitation r with little perturbation both on Efd and Ifd  %r=0.5*randn(size(t));
 
 r = r(1:1201);

  
  I2=Ifd + r; %I2 is the signal entering the AVR
  Ifd_old=Ifd;
  Ifd=I2; %% Ifd is the real current Ifd
  
  
  set_param(mdl,'SimulationCommand','Start') 
  pause(2)
  Efd_sim = out.Efd.data - mean(out.Efd.data(1:60));
 
  
  
  data2=iddata(Efd_sim,[V I2],Ts);
  
  %%%%% grey-box identification with the data generated by V and r
  model=greyest(data2,sys_init,opt);
  

  
  figure(3); bode(model,'r',sys_true,'b',logspace(-3,2.79,200));
  
  figure(4); compare(model,data2)
  

 
 



